/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/assistant/chat/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_assistant_chat_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Google OAuth2 sign-in
         * @description POST /auth/google/
         *
         *     Next.js integration
         *     -------------------
         *     1. Install: npm install @react-oauth/google
         *     2. Wrap your app in <GoogleOAuthProvider clientId="...">
         *     3. Use <GoogleLogin onSuccess={resp => postCredential(resp.credential)} />
         *     4. POST { credential: resp.credential } to this endpoint.
         *     5. Store the returned access + refresh tokens in httpOnly cookies or
         *        a secure state manager.
         *
         *     This view verifies the Google ID token with Google's public keys and
         *     creates/links the User automatically.
         */
        post: operations["v1_auth_google_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Email / password login
         * @description POST /auth/login/
         *     Returns an access + refresh JWT pair on valid credentials.
         */
        post: operations["v1_auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout (revoke session)
         * @description POST /auth/logout/
         *     Revokes the supplied refresh token (session).
         */
        post: operations["v1_auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/magic-link/request/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request passwordless magic link
         * @description POST /auth/magic-link/request/
         *     Sends a one-time login link to the given email.
         *     Always returns 200 to prevent email enumeration.
         */
        post: operations["v1_auth_magic_link_request_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/magic-link/verify/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify magic link token
         * @description POST /auth/magic-link/verify/
         *     Consumes the token from the magic-link URL and returns a JWT pair.
         */
        post: operations["v1_auth_magic_link_verify_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user profile
         * @description GET /auth/me/
         *     Returns the authenticated user's full profile.
         */
        get: operations["v1_auth_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me/change-password/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change password
         * @description POST /auth/me/change-password/
         *     Change password while authenticated.  All other sessions are revoked.
         */
        post: operations["v1_auth_me_change_password_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me/update/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update current user profile
         * @description PATCH /auth/me/update/
         *     Partially update the current user's name and/or profile.
         */
        patch: operations["v1_auth_me_update_partial_update"];
        trace?: never;
    };
    "/api/v1/auth/password-reset/confirm/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm password reset
         * @description POST /auth/password-reset/confirm/
         *     Validates the reset token and sets the new password.
         */
        post: operations["v1_auth_password_reset_confirm_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset/request/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request password reset
         * @description POST /auth/password-reset/request/
         *     Sends a password-reset email.
         *     Always returns 200.
         */
        post: operations["v1_auth_password_reset_request_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new user
         * @description POST /auth/register/
         *     Create a new CLIENT account and send an email verification link.
         *     Throttled to 5 requests/minute (see settings.REST_FRAMEWORK).
         */
        post: operations["v1_auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List active sessions
         * @description GET /auth/sessions/
         *     List all non-revoked, non-expired sessions for the current user.
         */
        get: operations["v1_auth_sessions_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions/{session_id}/revoke/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke a specific session
         * @description DELETE /auth/sessions/<id>/revoke/
         *     Revoke a specific session (device logout).
         */
        delete: operations["v1_auth_sessions_revoke_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh access token
         * @description POST /auth/token/refresh/
         *     Exchange a valid refresh token for a new access (+ rotated refresh) token.
         */
        post: operations["v1_auth_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-email/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify email address
         * @description POST /auth/verify-email/
         *     Accepts the raw token from the verification link.
         */
        post: operations["v1_auth_verify_email_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/blog/categories/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Mix into any ReadOnlyModelViewSet exposing published content publicly. */
        get: operations["v1_blog_categories_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/blog/categories/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Mix into any ReadOnlyModelViewSet exposing published content publicly. */
        get: operations["v1_blog_categories_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/blog/posts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Mix in AFTER PublicContentViewSetMixin on any viewset whose model's
         *     `slug` field lives inside django-parler's TranslatedFields (Service,
         *     CaseStudy, BlogPost, Industry) — `slug` isn't a real column on the base
         *     table, so DRF's default get_object() (which does queryset.get(slug=...))
         *     can't resolve it. This filters through the translations relation for
         *     the currently-resolved language instead, via parler's `.translated()`.
         */
        get: operations["v1_blog_posts_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/blog/posts/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Mix in AFTER PublicContentViewSetMixin on any viewset whose model's
         *     `slug` field lives inside django-parler's TranslatedFields (Service,
         *     CaseStudy, BlogPost, Industry) — `slug` isn't a real column on the base
         *     table, so DRF's default get_object() (which does queryset.get(slug=...))
         *     can't resolve it. This filters through the translations relation for
         *     the currently-resolved language instead, via parler's `.translated()`.
         */
        get: operations["v1_blog_posts_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/blog/tags/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Mix into any ReadOnlyModelViewSet exposing published content publicly. */
        get: operations["v1_blog_tags_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/blog/tags/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Mix into any ReadOnlyModelViewSet exposing published content publicly. */
        get: operations["v1_blog_tags_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/case-studies/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Mix in AFTER PublicContentViewSetMixin on any viewset whose model's
         *     `slug` field lives inside django-parler's TranslatedFields (Service,
         *     CaseStudy, BlogPost, Industry) — `slug` isn't a real column on the base
         *     table, so DRF's default get_object() (which does queryset.get(slug=...))
         *     can't resolve it. This filters through the translations relation for
         *     the currently-resolved language instead, via parler's `.translated()`.
         */
        get: operations["v1_case_studies_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/case-studies/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Mix in AFTER PublicContentViewSetMixin on any viewset whose model's
         *     `slug` field lives inside django-parler's TranslatedFields (Service,
         *     CaseStudy, BlogPost, Industry) — `slug` isn't a real column on the base
         *     table, so DRF's default get_object() (which does queryset.get(slug=...))
         *     can't resolve it. This filters through the translations relation for
         *     the currently-resolved language instead, via parler's `.translated()`.
         */
        get: operations["v1_case_studies_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/crm/bookings/availability/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET ?date=YYYY-MM-DD → open slots + remaining capacity for that date. */
        get: operations["v1_crm_bookings_availability_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/crm/bookings/consultations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_crm_bookings_consultations_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/crm/leads/contact/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_crm_leads_contact_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/crm/leads/quote/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_crm_leads_quote_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/crm/newsletter/subscribe/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_crm_newsletter_subscribe_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/faqs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Mix into any ReadOnlyModelViewSet exposing published content publicly. */
        get: operations["v1_faqs_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/faqs/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Mix into any ReadOnlyModelViewSet exposing published content publicly. */
        get: operations["v1_faqs_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/industries/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Mix in AFTER PublicContentViewSetMixin on any viewset whose model's
         *     `slug` field lives inside django-parler's TranslatedFields (Service,
         *     CaseStudy, BlogPost, Industry) — `slug` isn't a real column on the base
         *     table, so DRF's default get_object() (which does queryset.get(slug=...))
         *     can't resolve it. This filters through the translations relation for
         *     the currently-resolved language instead, via parler's `.translated()`.
         */
        get: operations["v1_industries_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/industries/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Mix in AFTER PublicContentViewSetMixin on any viewset whose model's
         *     `slug` field lives inside django-parler's TranslatedFields (Service,
         *     CaseStudy, BlogPost, Industry) — `slug` isn't a real column on the base
         *     table, so DRF's default get_object() (which does queryset.get(slug=...))
         *     can't resolve it. This filters through the translations relation for
         *     the currently-resolved language instead, via parler's `.translated()`.
         */
        get: operations["v1_industries_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/process-steps/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Mix into any ReadOnlyModelViewSet exposing published content publicly. */
        get: operations["v1_process_steps_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/process-steps/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Mix into any ReadOnlyModelViewSet exposing published content publicly. */
        get: operations["v1_process_steps_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/seo/settings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_seo_settings_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/seo/sitemap-urls/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Flat list of every published URL — same underlying data as /sitemap.xml, as JSON. */
        get: operations["v1_seo_sitemap_urls_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/service-categories/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Mix into any ReadOnlyModelViewSet exposing published content publicly. */
        get: operations["v1_service_categories_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/service-categories/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Mix into any ReadOnlyModelViewSet exposing published content publicly. */
        get: operations["v1_service_categories_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Mix in AFTER PublicContentViewSetMixin on any viewset whose model's
         *     `slug` field lives inside django-parler's TranslatedFields (Service,
         *     CaseStudy, BlogPost, Industry) — `slug` isn't a real column on the base
         *     table, so DRF's default get_object() (which does queryset.get(slug=...))
         *     can't resolve it. This filters through the translations relation for
         *     the currently-resolved language instead, via parler's `.translated()`.
         */
        get: operations["v1_services_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Mix in AFTER PublicContentViewSetMixin on any viewset whose model's
         *     `slug` field lives inside django-parler's TranslatedFields (Service,
         *     CaseStudy, BlogPost, Industry) — `slug` isn't a real column on the base
         *     table, so DRF's default get_object() (which does queryset.get(slug=...))
         *     can't resolve it. This filters through the translations relation for
         *     the currently-resolved language instead, via parler's `.translated()`.
         */
        get: operations["v1_services_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/team/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Mix into any ReadOnlyModelViewSet exposing published content publicly. */
        get: operations["v1_team_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/team/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Mix into any ReadOnlyModelViewSet exposing published content publicly. */
        get: operations["v1_team_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/technologies/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Mix into any ReadOnlyModelViewSet exposing published content publicly. */
        get: operations["v1_technologies_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/technologies/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Mix into any ReadOnlyModelViewSet exposing published content publicly. */
        get: operations["v1_technologies_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/testimonials/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Mix into any ReadOnlyModelViewSet exposing published content publicly. */
        get: operations["v1_testimonials_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/testimonials/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Mix into any ReadOnlyModelViewSet exposing published content publicly. */
        get: operations["v1_testimonials_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AvailableSlot: {
            /** Format: uuid */
            id: string;
            weekday: number;
            weekday_display: string;
            /** Format: time */
            start_time: string;
            /** Format: time */
            end_time: string;
            timezone: string;
            remaining_capacity: number;
        };
        /** @enum {unknown} */
        BlankEnum: "";
        /** @description Minimal public author info — never expose the full accounts.User record. */
        BlogAuthor: {
            /** Format: uuid */
            id: string;
            readonly full_name: string;
        };
        BlogCategory: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            slug: string;
            description?: string;
            /** Display order */
            order?: number;
        };
        /**
         * @description Mix into any content detail serializer whose model uses
         *     apps.core.models.SEOFieldsMixin + seo_translated_fields(). Produces a
         *     single `seo` object with everything needed to render <head> tags and
         *     JSON-LD on the frontend, with sensible fallbacks baked in server-side
         *     so the frontend doesn't have to know the fallback chain.
         */
        BlogPostDetail: {
            /** Format: uuid */
            readonly id: string;
            readonly slug: string;
            readonly title: string;
            readonly excerpt: string;
            readonly content: string;
            readonly category: components["schemas"]["BlogCategory"];
            readonly tags: components["schemas"]["BlogTag"][];
            readonly cover_image: components["schemas"]["MediaAsset"];
            readonly author: components["schemas"]["BlogAuthor"];
            /** Reading time (minutes) */
            reading_time_minutes?: number | null;
            views_count?: number;
            /** Featured */
            is_featured?: boolean;
            /** Format: date-time */
            published_at?: string | null;
            readonly seo: {
                [key: string]: unknown;
            };
        };
        BlogPostList: {
            /** Format: uuid */
            readonly id: string;
            readonly slug: string;
            readonly title: string;
            readonly excerpt: string;
            readonly category: components["schemas"]["BlogCategory"];
            readonly tags: components["schemas"]["BlogTag"][];
            readonly cover_image: components["schemas"]["MediaAsset"];
            readonly author: components["schemas"]["BlogAuthor"];
            /** Reading time (minutes) */
            reading_time_minutes?: number | null;
            /** Featured */
            is_featured?: boolean;
            /** Format: date-time */
            published_at?: string | null;
        };
        BlogTag: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            slug: string;
        };
        /**
         * @description * `under_10k` - Under $10,000
         *     * `10k_50k` - $10,000 – $50,000
         *     * `50k_150k` - $50,000 – $150,000
         *     * `150k_plus` - $150,000+
         *     * `not_specified` - Not Specified
         * @enum {string}
         */
        BudgetRangeEnum: "under_10k" | "10k_50k" | "50k_150k" | "150k_plus" | "not_specified";
        /**
         * @description Mix into any content detail serializer whose model uses
         *     apps.core.models.SEOFieldsMixin + seo_translated_fields(). Produces a
         *     single `seo` object with everything needed to render <head> tags and
         *     JSON-LD on the frontend, with sensible fallbacks baked in server-side
         *     so the frontend doesn't have to know the fallback chain.
         */
        CaseStudyDetail: {
            /** Format: uuid */
            readonly id: string;
            readonly slug: string;
            readonly title: string;
            readonly overview: string;
            readonly challenge: string;
            readonly solution: string;
            readonly results: string;
            client_name?: string;
            readonly client_industry: components["schemas"]["Industry"];
            readonly client_logo: components["schemas"]["MediaAsset"];
            readonly thumbnail: components["schemas"]["MediaAsset"];
            readonly technologies: components["schemas"]["Technology"][];
            readonly gallery: components["schemas"]["CaseStudyGalleryImage"][];
            /**
             * Live project URL
             * Format: uri
             */
            project_url?: string;
            /** Project duration (weeks) */
            project_duration_weeks?: number | null;
            /** Featured */
            is_featured?: boolean;
            /** Format: date-time */
            published_at?: string | null;
            readonly seo: {
                [key: string]: unknown;
            };
        };
        CaseStudyGalleryImage: {
            /** Format: uuid */
            id: string;
            media: components["schemas"]["MediaAsset"];
            caption: string;
            order: number;
        };
        CaseStudyList: {
            /** Format: uuid */
            readonly id: string;
            readonly slug: string;
            readonly title: string;
            client_name?: string;
            readonly client_industry: components["schemas"]["Industry"];
            readonly thumbnail: components["schemas"]["MediaAsset"];
            /** Featured */
            is_featured?: boolean;
            /** Display order */
            order?: number;
            /** Format: date-time */
            published_at?: string | null;
        };
        /**
         * @description Allows authenticated users to change their own password.
         *     OAuth-only users (no local password) should use the reset flow instead.
         */
        ChangePasswordRequest: {
            current_password: string;
            new_password: string;
            new_password_confirm: string;
            current_refresh?: string;
        };
        ChatRequestRequest: {
            session_id?: string;
            message: string;
            /** @default en */
            language: string;
            page_url?: string;
        };
        ChatResponse: {
            session_id: string;
            reply: string;
            lead_captured: boolean;
        };
        ConsultationBookingAck: {
            /** Format: uuid */
            readonly id: string;
            readonly lead: components["schemas"]["LeadAck"];
            /** Format: date */
            readonly scheduled_date: string;
            /** Format: time */
            readonly scheduled_time: string;
            readonly timezone: string;
            readonly meeting_type: components["schemas"]["MeetingTypeEnum"];
            readonly status: components["schemas"]["ConsultationBookingAckStatusEnum"];
        };
        /**
         * @description * `pending` - Pending Confirmation
         *     * `confirmed` - Confirmed
         *     * `rescheduled` - Rescheduled
         *     * `completed` - Completed
         *     * `cancelled` - Cancelled
         *     * `no_show` - No Show
         * @enum {string}
         */
        ConsultationBookingAckStatusEnum: "pending" | "confirmed" | "rescheduled" | "completed" | "cancelled" | "no_show";
        ConsultationBookingCreateRequest: {
            full_name: string;
            /** Format: email */
            email: string;
            phone?: string;
            company?: string;
            job_title?: string;
            message?: string;
            /** Format: uuid */
            service_interest?: string | null;
            /** Format: uuid */
            industry?: string | null;
            /** @default not_specified */
            budget_range: components["schemas"]["BudgetRangeEnum"];
            timeline?: components["schemas"]["TimelineEnum"] | components["schemas"]["BlankEnum"];
            utm_source?: string;
            utm_medium?: string;
            utm_campaign?: string;
            utm_term?: string;
            utm_content?: string;
            source_page?: string;
            /** @default en */
            language: string;
            /** Format: uuid */
            slot: string;
            /** Format: date */
            scheduled_date: string;
            /** Format: time */
            scheduled_time: string;
            /** @default video */
            meeting_type: components["schemas"]["MeetingTypeEnum"];
            timezone?: string;
            notes?: string;
        };
        ContactLeadCreateRequest: {
            full_name: string;
            /** Format: email */
            email: string;
            phone?: string;
            company?: string;
            job_title?: string;
            message?: string;
            /** Format: uuid */
            service_interest?: string | null;
            /** Format: uuid */
            industry?: string | null;
            /** @default not_specified */
            budget_range: components["schemas"]["BudgetRangeEnum"];
            timeline?: components["schemas"]["TimelineEnum"] | components["schemas"]["BlankEnum"];
            utm_source?: string;
            utm_medium?: string;
            utm_campaign?: string;
            utm_term?: string;
            utm_content?: string;
            source_page?: string;
            /** @default en */
            language: string;
        };
        /**
         * @description * `engineering` - Engineering
         *     * `design` - Design
         *     * `ai` - AI
         *     * `devops` - DevOps
         *     * `management` - Management
         *     * `sales` - Sales
         *     * `qa` - QA
         *     * `other` - Other
         * @enum {string}
         */
        DepartmentEnum: "engineering" | "design" | "ai" | "devops" | "management" | "sales" | "qa" | "other";
        /**
         * @description Standard credential login.
         *     Returns the validated user object via .validated_data["user"].
         */
        EmailLoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        /** @description Accepts the raw token from the verification link. */
        EmailVerifyRequest: {
            token: string;
        };
        FAQ: {
            /** Format: uuid */
            readonly id: string;
            readonly question: string;
            readonly answer: string;
            category?: components["schemas"]["FAQCategoryEnum"];
            /**
             * Related service
             * Format: uuid
             */
            service?: string | null;
            /** Display order */
            order?: number;
        };
        /**
         * @description * `general` - General
         *     * `pricing` - Pricing
         *     * `process` - Process
         *     * `service` - Service-specific
         * @enum {string}
         */
        FAQCategoryEnum: "general" | "pricing" | "process" | "service";
        /**
         * @description * `image` - Image
         *     * `video` - Video
         *     * `document` - Document
         *     * `audio` - Audio
         *     * `other` - Other
         * @enum {string}
         */
        FileTypeEnum: "image" | "video" | "document" | "audio" | "other";
        /**
         * @description Accepts the Google ID token (credential) sent by the Next.js frontend
         *     after the user completes the Google sign-in flow.
         *
         *     Flow
         *     ----
         *     1. Frontend: user clicks "Sign in with Google" (using @react-oauth/google).
         *     2. Google returns a credential (signed JWT / ID token).
         *     3. Frontend POSTs { "credential": "<id_token>" } to /api/auth/google/.
         *     4. Backend verifies the token with Google's public keys.
         *     5. Backend creates or fetches the User, returns access + refresh tokens.
         *
         *     The actual verification and user creation happen in AuthService.google_oauth().
         *     This serializer only checks that the field is present and non-empty.
         */
        GoogleOAuthRequest: {
            /** @description Google ID token returned by @react-oauth/google. */
            credential: string;
        };
        Industry: {
            /** Format: uuid */
            readonly id: string;
            readonly name: string;
            readonly slug: string;
            readonly description: string;
            icon?: string;
            /** Display order */
            order?: number;
        };
        LeadAck: {
            /** Format: uuid */
            readonly id: string;
            readonly lead_type: components["schemas"]["LeadTypeEnum"];
            readonly lead_type_display: string;
            readonly status: components["schemas"]["LeadAckStatusEnum"];
            /** Format: date-time */
            readonly created_at: string;
        };
        /**
         * @description * `new` - New
         *     * `contacted` - Contacted
         *     * `qualified` - Qualified
         *     * `proposal_sent` - Proposal Sent
         *     * `negotiation` - Negotiation
         *     * `won` - Won
         *     * `lost` - Lost
         *     * `spam` - Spam
         * @enum {string}
         */
        LeadAckStatusEnum: "new" | "contacted" | "qualified" | "proposal_sent" | "negotiation" | "won" | "lost" | "spam";
        /**
         * @description * `contact` - Contact Form
         *     * `quote` - Quote Request
         *     * `consultation` - Consultation Booking
         *     * `newsletter` - Newsletter Signup
         *     * `ai_assistant` - AI Assistant
         *     * `career` - Careers
         * @enum {string}
         */
        LeadTypeEnum: "contact" | "quote" | "consultation" | "newsletter" | "ai_assistant" | "career";
        /**
         * @description Accepts the refresh token so the session record can be revoked.
         *     The access token is short-lived (~15 min) so we don't need to blacklist it.
         */
        LogoutRequest: {
            refresh: string;
        };
        /**
         * @description Request a passwordless login link.
         *     Always returns 200 (prevents email enumeration).
         */
        MagicLinkRequestRequest: {
            /** Format: email */
            email: string;
        };
        /** @description Accepts the raw token from the magic link URL. */
        MagicLinkVerifyRequest: {
            token: string;
        };
        MediaAsset: {
            /** Format: uuid */
            readonly id: string;
            readonly url: string | null;
            alt_text?: string;
            caption?: string;
            /** Width (px) */
            width?: number | null;
            /** Height (px) */
            height?: number | null;
            file_type: components["schemas"]["FileTypeEnum"];
        };
        /**
         * @description * `video` - Video Call
         *     * `phone` - Phone Call
         *     * `in_person` - In Person
         * @enum {string}
         */
        MeetingTypeEnum: "video" | "phone" | "in_person";
        NewsletterSubscribeRequest: {
            /** Format: email */
            email: string;
            /** @default en */
            language: string;
            source?: string;
        };
        NewsletterSubscriberAck: {
            /** Format: uuid */
            readonly id: string;
            /** Format: email */
            readonly email: string;
            /** Active */
            readonly is_active: boolean;
            /** Format: date-time */
            readonly subscribed_at: string;
        };
        Organization: {
            legal_name: string;
            logo: string | null;
            /** Format: uri */
            url: string;
            social_profiles: unknown;
            /** Format: email */
            contact_email: string;
            contact_phone: string;
        };
        PaginatedBlogCategoryList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["BlogCategory"][];
        };
        PaginatedBlogPostListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["BlogPostList"][];
        };
        PaginatedBlogTagList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["BlogTag"][];
        };
        PaginatedCaseStudyListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["CaseStudyList"][];
        };
        PaginatedFAQList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["FAQ"][];
        };
        PaginatedIndustryList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Industry"][];
        };
        PaginatedProcessStepList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ProcessStep"][];
        };
        PaginatedServiceCategoryList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ServiceCategory"][];
        };
        PaginatedServiceListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ServiceList"][];
        };
        PaginatedTeamMemberList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["TeamMember"][];
        };
        PaginatedTechnologyList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Technology"][];
        };
        PaginatedTestimonialList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Testimonial"][];
        };
        /** @description Validates the raw reset token and new password. */
        PasswordResetConfirmRequest: {
            token: string;
            password: string;
            password_confirm: string;
        };
        /**
         * @description Triggers a password-reset email.
         *     Always returns 200 (prevents email enumeration).
         */
        PasswordResetRequestRequest: {
            /** Format: email */
            email: string;
        };
        /** @description Partial update for the User row (name, legal consent). */
        PatchedUserUpdateRequest: {
            full_name?: string;
            /** Format: date-time */
            terms_accepted_at?: string | null;
            /** Privacy policy version accepted */
            privacy_accepted_version?: string | null;
            profile?: components["schemas"]["UserProfileRequest"];
        };
        ProcessStep: {
            /** Format: uuid */
            readonly id: string;
            readonly title: string;
            readonly description: string;
            icon?: string;
            /** Display order */
            order?: number;
        };
        QuoteRequestCreateRequest: {
            full_name: string;
            /** Format: email */
            email: string;
            phone?: string;
            company?: string;
            job_title?: string;
            message?: string;
            /** Format: uuid */
            service_interest?: string | null;
            /** Format: uuid */
            industry?: string | null;
            /** @default not_specified */
            budget_range: components["schemas"]["BudgetRangeEnum"];
            timeline?: components["schemas"]["TimelineEnum"] | components["schemas"]["BlankEnum"];
            utm_source?: string;
            utm_medium?: string;
            utm_campaign?: string;
            utm_term?: string;
            utm_content?: string;
            source_page?: string;
            /** @default en */
            language: string;
            requested_services?: string[];
            project_description?: string;
            /** Format: decimal */
            estimated_budget_min?: string | null;
            /** Format: decimal */
            estimated_budget_max?: string | null;
            /** @default USD */
            currency: string;
        };
        SEOSettingsResponse: {
            site_name: string;
            default_meta_title_suffix: string;
            default_meta_description: string;
            default_og_image: string | null;
            organization: components["schemas"]["Organization"];
            google_site_verification: string;
            google_analytics_id: string;
            google_tag_manager_id: string;
        };
        ServiceCategory: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            slug: string;
            /** @description Icon identifier used by the frontend, e.g. 'lucide:cpu'. */
            icon?: string;
            /** Display order */
            order?: number;
        };
        /**
         * @description Mix into any content detail serializer whose model uses
         *     apps.core.models.SEOFieldsMixin + seo_translated_fields(). Produces a
         *     single `seo` object with everything needed to render <head> tags and
         *     JSON-LD on the frontend, with sensible fallbacks baked in server-side
         *     so the frontend doesn't have to know the fallback chain.
         */
        ServiceDetail: {
            /** Format: uuid */
            readonly id: string;
            readonly slug: string;
            readonly name: string;
            readonly short_description: string;
            readonly overview: string;
            readonly problems_we_solve: string;
            readonly features: string;
            readonly benefits: string;
            icon?: string;
            readonly hero_image: components["schemas"]["MediaAsset"];
            readonly category: components["schemas"]["ServiceCategory"];
            readonly technologies: components["schemas"]["Technology"][];
            readonly industries: components["schemas"]["Industry"][];
            readonly faqs: string;
            /** Featured */
            is_featured?: boolean;
            /** Format: date-time */
            published_at?: string | null;
            readonly seo: {
                [key: string]: unknown;
            };
        };
        ServiceList: {
            /** Format: uuid */
            readonly id: string;
            readonly slug: string;
            readonly name: string;
            readonly short_description: string;
            icon?: string;
            readonly hero_image: components["schemas"]["MediaAsset"];
            readonly category: components["schemas"]["ServiceCategory"];
            /** Featured */
            is_featured?: boolean;
            /** Display order */
            order?: number;
        };
        SitemapEntry: {
            path: string;
            lastmod: string;
            changefreq: string;
            /** Format: double */
            priority: number;
        };
        /**
         * @description * `manual` - Manual
         *     * `clutch` - Clutch
         *     * `google` - Google
         *     * `linkedin` - LinkedIn
         *     * `trustpilot` - Trustpilot
         * @enum {string}
         */
        SourceEnum: "manual" | "clutch" | "google" | "linkedin" | "trustpilot";
        TeamMember: {
            /** Format: uuid */
            readonly id: string;
            full_name: string;
            slug: string;
            role_title: string;
            department?: components["schemas"]["DepartmentEnum"];
            bio?: string;
            readonly photo: components["schemas"]["MediaAsset"];
            /** Format: uri */
            linkedin_url?: string;
            /** Format: uri */
            github_url?: string;
            /**
             * Twitter/X URL
             * Format: uri
             */
            twitter_url?: string;
            /** Leadership */
            is_leadership?: boolean;
            /** Display order */
            order?: number;
        };
        Technology: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            slug: string;
            category: components["schemas"]["TechnologyCategoryEnum"];
            icon?: string;
            /** Format: uri */
            website_url?: string;
            /** Display order */
            order?: number;
        };
        /**
         * @description * `frontend` - Frontend
         *     * `backend` - Backend
         *     * `database` - Database
         *     * `cloud` - Cloud
         *     * `ai` - AI
         *     * `enterprise` - Enterprise
         *     * `mobile` - Mobile
         *     * `devops` - DevOps
         *     * `other` - Other
         * @enum {string}
         */
        TechnologyCategoryEnum: "frontend" | "backend" | "database" | "cloud" | "ai" | "enterprise" | "mobile" | "devops" | "other";
        Testimonial: {
            /** Format: uuid */
            readonly id: string;
            client_name: string;
            client_role?: string;
            client_company?: string;
            readonly client_avatar: components["schemas"]["MediaAsset"];
            quote: string;
            /** @description 1 to 5 stars. */
            rating?: number;
            source?: components["schemas"]["SourceEnum"];
            /** Format: uri */
            source_url?: string;
            /** Format: uuid */
            related_case_study?: string | null;
            /** Format: uuid */
            related_service?: string | null;
            /** Featured */
            is_featured?: boolean;
            /** Display order */
            order?: number;
        };
        /**
         * @description * `asap` - ASAP
         *     * `within_1_month` - Within 1 month
         *     * `within_3_months` - Within 3 months
         *     * `within_6_months` - Within 6 months
         *     * `flexible` - Flexible
         * @enum {string}
         */
        TimelineEnum: "asap" | "within_1_month" | "within_3_months" | "within_6_months" | "flexible";
        /** @description Wraps SimpleJWT token refresh with device tracking. */
        TokenRefreshRequest: {
            refresh: string;
        };
        /**
         * @description Read-only representation of the authenticated user + nested profile.
         *     Returned from GET /api/auth/me/.
         */
        UserMe: {
            /** Format: uuid */
            readonly id: string;
            /**
             * Email address
             * Format: email
             * @description Primary login credential — normalised to lowercase.
             */
            readonly email: string;
            readonly full_name: string;
            role: string;
            /** Email verified */
            readonly is_email_verified: boolean;
            /** @description True when the account was created via Google OAuth (no local password). */
            readonly is_oauth_user: boolean;
            /**
             * Google profile picture URL
             * Format: uri
             */
            readonly google_picture_url: string;
            /** Format: uuid */
            readonly tenant: string | null;
            /** Format: date-time */
            readonly terms_accepted_at: string | null;
            /** Format: date-time */
            readonly created_at: string;
            readonly profile: components["schemas"]["UserProfile"];
        };
        /** @description Full read/update serializer for UserProfile. */
        UserProfile: {
            /** Format: date */
            date_of_birth?: string | null;
            phone_number?: string | null;
            /** Format: email */
            alternate_email?: string | null;
            /** Address line 1 */
            address_line1?: string;
            /** Address line 2 */
            address_line2?: string;
            city?: string;
            /** State/province */
            state_province?: string;
            postal_code?: string;
            /** @description ISO 3166-1 alpha-2 code, e.g. 'US', 'GB'. */
            country?: string;
            /**
             * Format: uri
             * @description Configure DEFAULT_FILE_STORAGE to use S3/GCS in production.
             */
            profile_picture?: string | null;
            bio?: string;
            preferences?: unknown;
            timezone?: string;
            language?: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /** @description Full read/update serializer for UserProfile. */
        UserProfileRequest: {
            /** Format: date */
            date_of_birth?: string | null;
            phone_number?: string | null;
            /** Format: email */
            alternate_email?: string | null;
            /** Address line 1 */
            address_line1?: string;
            /** Address line 2 */
            address_line2?: string;
            city?: string;
            /** State/province */
            state_province?: string;
            postal_code?: string;
            /** @description ISO 3166-1 alpha-2 code, e.g. 'US', 'GB'. */
            country?: string;
            /**
             * Format: binary
             * @description Configure DEFAULT_FILE_STORAGE to use S3/GCS in production.
             */
            profile_picture?: string | null;
            bio?: string;
            preferences?: unknown;
            timezone?: string;
            language?: string;
        };
        /** @description Read-only representation of an active session. */
        UserRefreshToken: {
            /** Format: uuid */
            readonly id: string;
            /** @description Human-readable label, e.g. 'Chrome 124 on Windows 11'. */
            readonly device_name: string;
            readonly ip_address: string | null;
            /** Format: date-time */
            readonly last_used_at: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly expires_at: string;
        };
        /**
         * @description Validates new-user registration data.
         *     Passwords are never stored in the serializer; hashing happens in AuthService.
         */
        UserRegistrationRequest: {
            /** Format: email */
            email: string;
            full_name: string;
            password: string;
            password_confirm: string;
            /** @default false */
            terms_accepted: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    v1_assistant_chat_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ChatRequestRequest"];
                "multipart/form-data": components["schemas"]["ChatRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
        };
    };
    v1_auth_google_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleOAuthRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["GoogleOAuthRequest"];
                "multipart/form-data": components["schemas"]["GoogleOAuthRequest"];
            };
        };
        responses: {
            /** @description Access + refresh tokens. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid Google credential. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailLoginRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["EmailLoginRequest"];
                "multipart/form-data": components["schemas"]["EmailLoginRequest"];
            };
        };
        responses: {
            /** @description Access + refresh tokens. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid credentials. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LogoutRequest"];
                "multipart/form-data": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Logged out. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_auth_magic_link_request_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MagicLinkRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["MagicLinkRequestRequest"];
                "multipart/form-data": components["schemas"]["MagicLinkRequestRequest"];
            };
        };
        responses: {
            /** @description Magic link sent (if email exists). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_auth_magic_link_verify_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MagicLinkVerifyRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["MagicLinkVerifyRequest"];
                "multipart/form-data": components["schemas"]["MagicLinkVerifyRequest"];
            };
        };
        responses: {
            /** @description Access + refresh tokens. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMe"];
                };
            };
        };
    };
    v1_auth_me_change_password_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ChangePasswordRequest"];
                "multipart/form-data": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_auth_me_update_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUserUpdateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUserUpdateRequest"];
                "multipart/form-data": components["schemas"]["PatchedUserUpdateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMe"];
                };
            };
        };
    };
    v1_auth_password_reset_confirm_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirmRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordResetConfirmRequest"];
                "multipart/form-data": components["schemas"]["PasswordResetConfirmRequest"];
            };
        };
        responses: {
            /** @description Password updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_auth_password_reset_request_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordResetRequestRequest"];
                "multipart/form-data": components["schemas"]["PasswordResetRequestRequest"];
            };
        };
        responses: {
            /** @description Reset email sent (if exists). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRegistrationRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["UserRegistrationRequest"];
                "multipart/form-data": components["schemas"]["UserRegistrationRequest"];
            };
        };
        responses: {
            /** @description User created; verification email sent. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_auth_sessions_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRefreshToken"][];
                };
            };
        };
    };
    v1_auth_sessions_revoke_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_auth_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefreshRequest"];
                "multipart/form-data": components["schemas"]["TokenRefreshRequest"];
            };
        };
        responses: {
            /** @description New access token. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_auth_verify_email_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailVerifyRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["EmailVerifyRequest"];
                "multipart/form-data": components["schemas"]["EmailVerifyRequest"];
            };
        };
        responses: {
            /** @description Email verified. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_blog_categories_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedBlogCategoryList"];
                };
            };
        };
    };
    v1_blog_categories_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlogCategory"];
                };
            };
        };
    };
    v1_blog_posts_list: {
        parameters: {
            query?: {
                category?: string;
                is_featured?: boolean;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
                tag?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedBlogPostListList"];
                };
            };
        };
    };
    v1_blog_posts_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlogPostDetail"];
                };
            };
        };
    };
    v1_blog_tags_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedBlogTagList"];
                };
            };
        };
    };
    v1_blog_tags_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlogTag"];
                };
            };
        };
    };
    v1_case_studies_list: {
        parameters: {
            query?: {
                industry?: string;
                is_featured?: boolean;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
                service?: string;
                technology?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCaseStudyListList"];
                };
            };
        };
    };
    v1_case_studies_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseStudyDetail"];
                };
            };
        };
    };
    v1_crm_bookings_availability_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailableSlot"][];
                };
            };
        };
    };
    v1_crm_bookings_consultations_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsultationBookingCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ConsultationBookingCreateRequest"];
                "multipart/form-data": components["schemas"]["ConsultationBookingCreateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsultationBookingAck"];
                };
            };
        };
    };
    v1_crm_leads_contact_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactLeadCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ContactLeadCreateRequest"];
                "multipart/form-data": components["schemas"]["ContactLeadCreateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadAck"];
                };
            };
        };
    };
    v1_crm_leads_quote_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuoteRequestCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["QuoteRequestCreateRequest"];
                "multipart/form-data": components["schemas"]["QuoteRequestCreateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadAck"];
                };
            };
        };
    };
    v1_crm_newsletter_subscribe_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewsletterSubscribeRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["NewsletterSubscribeRequest"];
                "multipart/form-data": components["schemas"]["NewsletterSubscribeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsletterSubscriberAck"];
                };
            };
        };
    };
    v1_faqs_list: {
        parameters: {
            query?: {
                /**
                 * @description * `general` - General
                 *     * `pricing` - Pricing
                 *     * `process` - Process
                 *     * `service` - Service-specific
                 */
                category?: "general" | "pricing" | "process" | "service";
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
                service?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedFAQList"];
                };
            };
        };
    };
    v1_faqs_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this FAQ. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FAQ"];
                };
            };
        };
    };
    v1_industries_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedIndustryList"];
                };
            };
        };
    };
    v1_industries_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Industry"];
                };
            };
        };
    };
    v1_process_steps_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProcessStepList"];
                };
            };
        };
    };
    v1_process_steps_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this process step. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessStep"];
                };
            };
        };
    };
    v1_seo_settings_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SEOSettingsResponse"];
                };
            };
        };
    };
    v1_seo_sitemap_urls_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SitemapEntry"][];
                };
            };
        };
    };
    v1_service_categories_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedServiceCategoryList"];
                };
            };
        };
    };
    v1_service_categories_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceCategory"];
                };
            };
        };
    };
    v1_services_list: {
        parameters: {
            query?: {
                category?: string;
                industry?: string;
                is_featured?: boolean;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
                technology?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedServiceListList"];
                };
            };
        };
    };
    v1_services_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceDetail"];
                };
            };
        };
    };
    v1_team_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTeamMemberList"];
                };
            };
        };
    };
    v1_team_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this team member. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMember"];
                };
            };
        };
    };
    v1_technologies_list: {
        parameters: {
            query?: {
                /**
                 * @description * `frontend` - Frontend
                 *     * `backend` - Backend
                 *     * `database` - Database
                 *     * `cloud` - Cloud
                 *     * `ai` - AI
                 *     * `enterprise` - Enterprise
                 *     * `mobile` - Mobile
                 *     * `devops` - DevOps
                 *     * `other` - Other
                 */
                category?: "ai" | "backend" | "cloud" | "database" | "devops" | "enterprise" | "frontend" | "mobile" | "other";
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTechnologyList"];
                };
            };
        };
    };
    v1_technologies_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Technology"];
                };
            };
        };
    };
    v1_testimonials_list: {
        parameters: {
            query?: {
                is_featured?: boolean;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                related_case_study?: string;
                related_service?: string;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTestimonialList"];
                };
            };
        };
    };
    v1_testimonials_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this testimonial. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Testimonial"];
                };
            };
        };
    };
}
