// lib/seo/metadata.ts
import { Metadata } from "next";
import { SeoMetadataOptions, PageType } from "./types";
import { getAlternates } from "./alternates";
import { getKeywords } from "./keywords";
import { getOgLocale, SupportedLocale } from "@/lib/locale";

const BASE_URL = "https://automex.tech";

const titleTemplates: Record<PageType, Record<SupportedLocale, string>> = {
  home: {
    en: "AUTOMEX - AI Solutions, Software Development & Digital Transformation",
    es: "AUTOMEX - Soluciones de IA, Desarrollo de Software y Transformación Digital",
    de: "AUTOMEX - KI-Lösungen, Softwareentwicklung & Digitale Transformation",
    fr: "AUTOMEX - Solutions IA, Développement Logiciel & Transformation Digitale",
    it: "AUTOMEX - Soluzioni IA, Sviluppo Software & Trasformazione Digitale",
    nl: "AUTOMEX - AI Oplossingen, Softwareontwikkeling & Digitale Transformatie",
    zh: "AUTOMEX - AI解决方案、软件开发与数字化转型",
    ar: "AUTOMEX - حلول الذكاء الاصطناعي وتطوير البرمجيات والتحول الرقمي",
    fa: "AUTOMEX - راهکارهای هوش مصنوعی، توسعه نرم‌افزار و تحول دیجیتال",
    ps: "AUTOMEX - AI حل لارې، سافټویر پراختیا او ډیجیټل بدلون",
  },
  about: {
    en: "About AUTOMEX - AI & Technology Solutions Company",
    es: "Sobre AUTOMEX - Empresa de Soluciones de IA y Tecnología",
    de: "Über AUTOMEX - KI- und Technologielösungen Unternehmen",
    fr: "À Propos d'AUTOMEX - Entreprise de Solutions IA et Technologie",
    it: "Chi Siamo AUTOMEX - Azienda di Soluzioni IA e Tecnologia",
    nl: "Over AUTOMEX - AI- en Technologieoplossingen Bedrijf",
    zh: "关于AUTOMEX - AI与技术解决方案公司",
    ar: "حول AUTOMEX - شركة حلول الذكاء الاصطناعي والتكنولوجيا",
    fa: "درباره AUTOMEX - شرکت راهکارهای هوش مصنوعی و فناوری",
    ps: "د AUTOMEX په اړه - د AI او ټکنالوژۍ حل لارې شرکت",
  },
  contact: {
    en: "Contact AUTOMEX - Get in Touch with Our Team",
    es: "Contacta AUTOMEX - Ponte en Contacto con Nuestro Equipo",
    de: "Kontakt AUTOMEX - Nehmen Sie Kontakt mit Unserem Team auf",
    fr: "Contact AUTOMEX - Prenez Contact avec Notre Équipe",
    it: "Contatta AUTOMEX - Mettiti in Contatto con il Nostro Team",
    nl: "Contact AUTOMEX - Neem Contact Op met Ons Team",
    zh: "联系AUTOMEX - 与我们的团队取得联系",
    ar: "اتصل بـ AUTOMEX - تواصل مع فريقنا",
    fa: "تماس با AUTOMEX - با تیم ما در تماس باشید",
    ps: "د AUTOMEX سره اړیکه - زموږ ټیم سره اړیکه ونیسئ",
  },
  crm: {
    en: "CRM Overview – AUTOMEX Customer Management",
    es: "CRM – AUTOMEX Gestión de Clientes",
    de: "CRM-Übersicht – AUTOMEX Kundenmanagement",
    fr: "Aperçu CRM – AUTOMEX Gestion de la Clientèle",
    it: "Panoramica CRM – AUTOMEX Gestione Clienti",
    nl: "CRM Overzicht – AUTOMEX Klantbeheer",
    zh: "CRM总览 – AUTOMEX 客户管理",
    ar: "نظرة عامة على CRM – AUTOMEX إدارة العملاء",
    fa: "نمای کلی CRM – AUTOMEX مدیریت مشتریان",
    ps: "د CRM عمومي کتنه – AUTOMEX د پیرودونکو مدیریت",
  },
  bookCall: {
    en: "Book a Call – AUTOMEX Free Consultation",
    es: "Reservar una Llamada – AUTOMEX Consulta Gratuita",
    de: "Gespräch buchen – AUTOMEX Kostenlose Beratung",
    fr: "Réserver un Appel – AUTOMEX Consultation Gratuite",
    it: "Prenota una Chiamata – AUTOMEX Consulenza Gratuita",
    nl: "Belafspraak Boeken – AUTOMEX Gratis Consult",
    zh: "预约通话 – AUTOMEX 免费咨询",
    ar: "احجز مكالمة – AUTOMEX استشارة مجانية",
    fa: "رزرو تماس – AUTOMEX مشاوره رایگان",
    ps: "زنګ بک کړئ – AUTOMEX وړیا مشوره",
  },
  contactSales: {
    en: "Contact Sales – AUTOMEX Enterprise Sales",
    es: "Contactar Ventas – AUTOMEX Ventas Empresariales",
    de: "Vertrieb kontaktieren – AUTOMEX Enterprise Sales",
    fr: "Contacter les Ventes – AUTOMEX Ventes Entreprise",
    it: "Contatta le Vendite – AUTOMEX Vendite Aziendali",
    nl: "Contact Verkoop – AUTOMEX Enterprise Sales",
    zh: "联系销售 – AUTOMEX 企业销售",
    ar: "اتصل بالمبيعات – AUTOMEX مبيعات الشركات",
    fa: "تماس با فروش – AUTOMEX فروش سازمانی",
    ps: "د پلور سره اړیکه – AUTOMEX تصدۍ پلور",
  },
  quote: {
    en: "Request a Quote – AUTOMEX AI & Development",
    es: "Solicitar Presupuesto – AUTOMEX IA y Desarrollo",
    de: "Angebot anfordern – AUTOMEX KI & Entwicklung",
    fr: "Demander un Devis – AUTOMEX IA & Développement",
    it: "Richiedi un Preventivo – AUTOMEX IA & Sviluppo",
    nl: "Offerte Aanvragen – AUTOMEX AI & Ontwikkeling",
    zh: "请求报价 – AUTOMEX AI与开发",
    ar: "طلب عرض سعر – AUTOMEX الذكاء الاصطناعي والتطوير",
    fa: "درخواست پیش‌فاکتور – AUTOMEX هوش مصنوعی و توسعه",
    ps: "د نرخ غوښتنه – AUTOMEX AI او پراختیا",
  },
  services: {
    en: "Services – AUTOMEX AI, Software & Digital Transformation",
    es: "Servicios – AUTOMEX IA, Software y Transformación Digital",
    de: "Dienstleistungen – AUTOMEX KI, Software & Digitale Transformation",
    fr: "Services – AUTOMEX IA, Logiciel & Transformation Digitale",
    it: "Servizi – AUTOMEX IA, Software & Trasformazione Digitale",
    nl: "Diensten – AUTOMEX AI, Software & Digitale Transformatie",
    zh: "服务 – AUTOMEX AI、软件与数字化转型",
    ar: "الخدمات – AUTOMEX الذكاء الاصطناعي والبرمجيات والتحول الرقمي",
    fa: "خدمات – AUTOMEX هوش مصنوعی، نرم‌افزار و تحول دیجیتال",
    ps: "خدمات – AUTOMEX AI، سافټویر او ډیجیټل بدلون",
  },
  serviceDetail: {
    en: "AUTOMEX – AI & Software Development Service",
    es: "AUTOMEX – Servicio de Desarrollo de IA y Software",
    de: "AUTOMEX – KI- und Softwareentwicklungsdienst",
    fr: "AUTOMEX – Service de Développement IA et Logiciel",
    it: "AUTOMEX – Servizio di Sviluppo IA e Software",
    nl: "AUTOMEX – AI- en Softwareontwikkelingsdienst",
    zh: "AUTOMEX – AI与软件开发服务",
    ar: "AUTOMEX – خدمة تطوير الذكاء الاصطناعي والبرمجيات",
    fa: "AUTOMEX – سرویس توسعه هوش مصنوعی و نرم‌افزار",
    ps: "AUTOMEX – د AI او سافټویر پراختیا خدمت",
  },
  techExpertise: {
    en: "Tech Expertise – AUTOMEX Technology Capabilities & Stack",
    es: "Experiencia Técnica – AUTOMEX Capacidades y Stack Tecnológico",
    de: "Tech-Expertise – AUTOMEX Technologiefähigkeiten & Stack",
    fr: "Expertise Technique – AUTOMEX Capacités et Stack Technologique",
    it: "Competenze Tecniche – AUTOMEX Capacità e Stack Tecnologico",
    nl: "Tech Expertise – AUTOMEX Technologiecapaciteiten & Stack",
    zh: "技术专长 – AUTOMEX 技术能力与技术栈",
    ar: "الخبرة التقنية – AUTOMEX قدرات ومكدس التكنولوجيا",
    fa: "تخصص فنی – AUTOMEX قابلیت‌ها و پشته فناوری",
    ps: "تخنیکي تخصص – AUTOMEX ټکنالوژۍ وړتیاوې او سټک",
  },
  techExpertiseDetail: {
    en: "AUTOMEX – Tech Expertise",
    es: "AUTOMEX – Experiencia Técnica",
    de: "AUTOMEX – Tech-Expertise",
    fr: "AUTOMEX – Expertise Technique",
    it: "AUTOMEX – Competenza Tecnica",
    nl: "AUTOMEX – Tech Expertise",
    zh: "AUTOMEX – 技术专长",
    ar: "AUTOMEX – الخبرة التقنية",
    fa: "AUTOMEX – تخصص فنی",
    ps: "AUTOMEX – تخنیکي تخصص",
  },
  industries: {
    en: "Industries – AUTOMEX AI & Technology Solutions by Sector",
    es: "Industrias – AUTOMEX Soluciones de IA y Tecnología por Sector",
    de: "Branchen – AUTOMEX KI- & Technologielösungen nach Sektor",
    fr: "Industries – AUTOMEX Solutions IA & Technologie par Secteur",
    it: "Industrie – AUTOMEX Soluzioni IA & Tecnologia per Settore",
    nl: "Industrieën – AUTOMEX AI- & Technologieoplossingen per Sector",
    zh: "行业 – AUTOMEX 各行业AI与技术解决方案",
    ar: "الصناعات – AUTOMEX حلول الذكاء الاصطناعي والتكنولوجيا حسب القطاع",
    fa: "صنایع – AUTOMEX راهکارهای هوش مصنوعی و فناوری بر اساس بخش",
    ps: "صنعتونه – AUTOMEX د سکټور له مخې AI او ټکنالوژۍ حل لارې",
  },
  industryDetail: {
    en: "AUTOMEX – Industry Technology Solutions",
    es: "AUTOMEX – Soluciones Tecnológicas para la Industria",
    de: "AUTOMEX – Technologielösungen für die Branche",
    fr: "AUTOMEX – Solutions Technologiques pour l'Industrie",
    it: "AUTOMEX – Soluzioni Tecnologiche per l'Industria",
    nl: "AUTOMEX – Technologieoplossingen voor de Industrie",
    zh: "AUTOMEX – 行业技术解决方案",
    ar: "AUTOMEX – حلول تقنية للصناعة",
    fa: "AUTOMEX – راهکارهای فناوری برای صنعت",
    ps: "AUTOMEX – د صنعت لپاره ټکنالوژۍ حل لارې",
  },
  aiCapabilities: {
    en: "AI Capabilities – AUTOMEX Artificial Intelligence Solutions",
    es: "Capacidades de IA – AUTOMEX Soluciones de Inteligencia Artificial",
    de: "KI-Fähigkeiten – AUTOMEX Lösungen für Künstliche Intelligenz",
    fr: "Capacités IA – AUTOMEX Solutions d'Intelligence Artificielle",
    it: "Capacità IA – AUTOMEX Soluzioni di Intelligenza Artificiale",
    nl: "AI-Mogelijkheden – AUTOMEX Kunstmatige Intelligentie Oplossingen",
    zh: "AI能力 – AUTOMEX 人工智能解决方案",
    ar: "قدرات الذكاء الاصطناعي – AUTOMEX حلول الذكاء الاصطناعي",
    fa: "قابلیت‌های هوش مصنوعی – AUTOMEX راهکارهای هوش مصنوعی",
    ps: "د AI وړتیاوې – AUTOMEX مصنوعي ځیرکتیا حل لارې",
  },
  aiCapabilityDetail: {
    en: "AUTOMEX – AI Capability",
    es: "AUTOMEX – Capacidad de IA",
    de: "AUTOMEX – KI-Fähigkeit",
    fr: "AUTOMEX – Capacité IA",
    it: "AUTOMEX – Capacità IA",
    nl: "AUTOMEX – AI-Mogelijkheid",
    zh: "AUTOMEX – AI能力",
    ar: "AUTOMEX – قدرة الذكاء الاصطناعي",
    fa: "AUTOMEX – قابلیت هوش مصنوعی",
    ps: "AUTOMEX – د AI وړتیا",
  },
  caseStudies: {
    en: "Case Studies – AUTOMEX Success Stories & Client Projects",
    es: "Casos de Estudio – AUTOMEX Historias de Éxito y Proyectos de Clientes",
    de: "Fallstudien – AUTOMEX Erfolgsgeschichten & Kundenprojekte",
    fr: "Études de Cas – AUTOMEX Histoires de Réussite et Projets Clients",
    it: "Casi Studio – AUTOMEX Storie di Successo e Progetti Clienti",
    nl: "Casestudies – AUTOMEX Succesverhalen & Klantprojecten",
    zh: "案例研究 – AUTOMEX 成功案例与客户项目",
    ar: "دراسات الحالة – AUTOMEX قصص نجاح ومشاريع العملاء",
    fa: "مطالعات موردی – AUTOMEX داستان‌های موفقیت و پروژه‌های مشتری",
    ps: "د قضیې مطالعې – AUTOMEX د بریالیتوب کیسې او د پیرودونکي پروژې",
  },
  caseStudyDetail: {
    en: "AUTOMEX – Case Study",
    es: "AUTOMEX – Caso de Estudio",
    de: "AUTOMEX – Fallstudie",
    fr: "AUTOMEX – Étude de Cas",
    it: "AUTOMEX – Caso Studio",
    nl: "AUTOMEX – Casestudie",
    zh: "AUTOMEX – 案例研究",
    ar: "AUTOMEX – دراسة حالة",
    fa: "AUTOMEX – مطالعه موردی",
    ps: "AUTOMEX – د قضیې مطالعه",
  },
  portfolio: {
    en: "Portfolio – AUTOMEX Projects, Case Studies & Client Work",
    es: "Portafolio – AUTOMEX Proyectos, Casos de Estudio y Trabajo con Clientes",
    de: "Portfolio – AUTOMEX Projekte, Fallstudien & Kundenarbeiten",
    fr: "Portfolio – AUTOMEX Projets, Études de Cas & Travaux Clients",
    it: "Portfolio – AUTOMEX Progetti, Casi Studio & Lavori per Clienti",
    nl: "Portfolio – AUTOMEX Projecten, Casestudies & Klantwerk",
    zh: "作品集 – AUTOMEX 项目、案例研究与客户作品",
    ar: "المحفظة – AUTOMEX مشاريع ودراسات حالة وأعمال العملاء",
    fa: "نمونه کارها – AUTOMEX پروژه‌ها، مطالعات موردی و کارهای مشتری",
    ps: "پورټ فولیو – AUTOMEX پروژې، د قضیې مطالعې او د پیرودونکي کار",
  },
  portfolioDetail: {
    en: "AUTOMEX – Portfolio Project",
    es: "AUTOMEX – Proyecto del Portafolio",
    de: "AUTOMEX – Portfolio-Projekt",
    fr: "AUTOMEX – Projet du Portfolio",
    it: "AUTOMEX – Progetto del Portfolio",
    nl: "AUTOMEX – Portfolio Project",
    zh: "AUTOMEX – 作品集项目",
    ar: "AUTOMEX – مشروع المحفظة",
    fa: "AUTOMEX – پروژه نمونه کار",
    ps: "AUTOMEX – د پورټ فولیو پروژه",
  },
  blog: {
    en: "Blog – AUTOMEX Insights on AI, Software & Technology",
    es: "Blog – AUTOMEX Información sobre IA, Software y Tecnología",
    de: "Blog – AUTOMEX Einblicke in KI, Software & Technologie",
    fr: "Blog – AUTOMEX Aperçus sur l'IA, les Logiciels et la Technologie",
    it: "Blog – AUTOMEX Approfondimenti su IA, Software e Tecnologia",
    nl: "Blog – AUTOMEX Inzichten over AI, Software & Technologie",
    zh: "博客 – AUTOMEX AI、软件与技术洞察",
    ar: "المدونة – AUTOMEX رؤى حول الذكاء الاصطناعي والبرمجيات والتكنولوجيا",
    fa: "وبلاگ – AUTOMEX بینش‌های هوش مصنوعی، نرم‌افزار و فناوری",
    ps: "بلاګ – AUTOMEX د AI، سافټویر او ټکنالوژۍ لیدونه",
  },
  blogDetail: {
    en: "AUTOMEX Blog",
    es: "Blog de AUTOMEX",
    de: "AUTOMEX Blog",
    fr: "Blog AUTOMEX",
    it: "Blog AUTOMEX",
    nl: "AUTOMEX Blog",
    zh: "AUTOMEX 博客",
    ar: "مدونة AUTOMEX",
    fa: "وبلاگ AUTOMEX",
    ps: "د AUTOMEX بلاګ",
  },
  privacy: {
    en: "Privacy Policy – AUTOMEX",
    es: "Política de Privacidad – AUTOMEX",
    de: "Datenschutzerklärung – AUTOMEX",
    fr: "Politique de Confidentialité – AUTOMEX",
    it: "Informativa sulla Privacy – AUTOMEX",
    nl: "Privacybeleid – AUTOMEX",
    zh: "隐私政策 – AUTOMEX",
    ar: "سياسة الخصوصية – AUTOMEX",
    fa: "سیاست حفظ حریم خصوصی – AUTOMEX",
    ps: "د خصوصیت پالیسي – AUTOMEX",
  },
  terms: {
    en: "Terms of Service – AUTOMEX",
    es: "Términos de Servicio – AUTOMEX",
    de: "Nutzungsbedingungen – AUTOMEX",
    fr: "Conditions d'Utilisation – AUTOMEX",
    it: "Termini di Servizio – AUTOMEX",
    nl: "Algemene Voorwaarden – AUTOMEX",
    zh: "服务条款 – AUTOMEX",
    ar: "شروط الخدمة – AUTOMEX",
    fa: "شرایط خدمات – AUTOMEX",
    ps: "د خدماتو شرایط – AUTOMEX",
  },
};

const defaultDescriptions: Record<PageType, Record<SupportedLocale, string>> = {
  home: {
    en: "AUTOMEX delivers AI solutions, custom software development, web & mobile apps, and digital transformation services to help businesses scale and innovate.",
    es: "AUTOMEX ofrece soluciones de IA, desarrollo de software personalizado, aplicaciones web y móviles, y servicios de transformación digital para ayudar a las empresas a escalar e innovar.",
    de: "AUTOMEX bietet KI-Lösungen, individuelle Softwareentwicklung, Web- und Mobile-Apps sowie digitale Transformationsdienste, um Unternehmen bei der Skalierung und Innovation zu helfen.",
    fr: "AUTOMEX fournit des solutions IA, du développement logiciel personnalisé, des applications web et mobiles, et des services de transformation digitale pour aider les entreprises à évoluer et innover.",
    it: "AUTOMEX fornisce soluzioni IA, sviluppo software personalizzato, app web e mobili, e servizi di trasformazione digitale per aiutare le aziende a crescere e innovare.",
    nl: "AUTOMEX biedt AI-oplossingen, maatwerk softwareontwikkeling, web- en mobiele apps, en digitale transformatiediensten om bedrijven te helpen schalen en innoveren.",
    zh: "AUTOMEX提供AI解决方案、定制软件开发、网站与移动应用，以及数字化转型服务，帮助企业扩展和创新。",
    ar: "تقدم AUTOMEX حلول الذكاء الاصطناعي، وتطوير البرمجيات المخصصة، وتطبيقات الويب والجوال، وخدمات التحول الرقمي لمساعدة الشركات على النمو والابتكار.",
    fa: "AUTOMEX راهکارهای هوش مصنوعی، توسعه نرم‌افزار سفارشی، اپلیکیشن‌های وب و موبایل، و خدمات تحول دیجیتال را برای کمک به کسب‌وکارها در رشد و نوآوری ارائه می‌دهد.",
    ps: "AUTOMEX د AI حل لارې، دودیز سافټویر پراختیا، ویب او موبایل اپلیکیشنونه، او د ډیجیټل بدلون خدمتونه وړاندې کوي ترڅو سوداګرۍ ته د ودې او نوښت په برخه کې مرسته وکړي.",
  },
  about: {
    en: "Learn about AUTOMEX - our mission, values, and how we help businesses transform through AI, software, and technology solutions.",
    es: "Conoce AUTOMEX - nuestra misión, valores, y cómo ayudamos a las empresas a transformarse a través de soluciones de IA, software y tecnología.",
    de: "Erfahren Sie mehr über AUTOMEX - unsere Mission, Werte und wie wir Unternehmen durch KI-, Software- und Technologielösungen bei der Transformation helfen.",
    fr: "Découvrez AUTOMEX - notre mission, nos valeurs, et comment nous aidons les entreprises à se transformer grâce aux solutions IA, logiciels et technologies.",
    it: "Scopri AUTOMEX - la nostra missione, i nostri valori e come aiutiamo le aziende a trasformarsi attraverso soluzioni IA, software e tecnologia.",
    nl: "Leer AUTOMEX kennen - onze missie, waarden en hoe we bedrijven helpen transformeren door AI-, software- en technologieoplossingen.",
    zh: "了解AUTOMEX - 我们的使命、价值观，以及我们如何通过AI、软件和技术解决方案帮助企业转型。",
    ar: "تعرف على AUTOMEX - مهمتنا وقيمنا، وكيف نساعد الشركات على التحول من خلال حلول الذكاء الاصطناعي والبرمجيات والتكنولوجيا.",
    fa: "با AUTOMEX آشنا شوید - مأموریت، ارزش‌ها، و نحوه کمک ما به کسب‌وکارها برای تحول از طریق راهکارهای هوش مصنوعی، نرم‌افزار و فناوری.",
    ps: "د AUTOMEX په اړه زده کړئ - زموږ ماموریت، ارزښتونه، او څنګه موږ د AI، سافټویر او ټکنالوژۍ حل لارو له لارې سوداګرۍ سره بدلون کې مرسته کوو.",
  },
  contact: {
    en: "Contact AUTOMEX for AI solutions, software development, and digital transformation services. Get in touch with our team today.",
    es: "Contacta AUTOMEX para soluciones de IA, desarrollo de software y servicios de transformación digital. Ponte en contacto con nuestro equipo hoy.",
    de: "Kontaktieren Sie AUTOMEX für KI-Lösungen, Softwareentwicklung und digitale Transformationsdienste. Nehmen Sie noch heute Kontakt mit unserem Team auf.",
    fr: "Contactez AUTOMEX pour des solutions IA, du développement logiciel et des services de transformation digitale. Prenez contact avec notre équipe aujourd'hui.",
    it: "Contatta AUTOMEX per soluzioni IA, sviluppo software e servizi di trasformazione digitale. Mettiti in contatto con il nostro team oggi.",
    nl: "Contact AUTOMEX voor AI-oplossingen, softwareontwikkeling en digitale transformatiediensten. Neem vandaag nog contact op met ons team.",
    zh: "联系AUTOMEX获取AI解决方案、软件开发和数字化转型服务。今天就与我们的团队取得联系。",
    ar: "اتصل بـ AUTOMEX للحصول على حلول الذكاء الاصطناعي، تطوير البرمجيات، وخدمات التحول الرقمي. تواصل مع فريقنا اليوم.",
    fa: "برای راهکارهای هوش مصنوعی، توسعه نرم‌افزار و خدمات تحول دیجیتال با AUTOMEX تماس بگیرید. امروز با تیم ما در تماس باشید.",
    ps: "د AI حل لارو، سافټویر پراختیا او ډیجیټل بدلون خدمتونو لپاره د AUTOMEX سره اړیکه ونیسئ. نن ورځ زموږ ټیم سره اړیکه ونیسئ.",
  },
  crm: {
    en: "Manage leads, automate follow‑ups, and track customer interactions with AUTOMEX CRM. Streamline your sales process and grow your business.",
    es: "Gestione clientes potenciales, automatice seguimientos y realice un seguimiento de las interacciones con los clientes con el CRM de AUTOMEX. Optimice su proceso de ventas y haga crecer su negocio.",
    de: "Verwalten Sie Leads, automatisieren Sie Follow‑ups und verfolgen Sie Kundeninteraktionen mit AUTOMEX CRM. Optimieren Sie Ihren Verkaufsprozess und wachsen Sie Ihr Geschäft.",
    fr: "Gérez vos prospects, automatisez les relances et suivez les interactions clients avec le CRM AUTOMEX. Rationalisez votre processus de vente et développez votre entreprise.",
    it: "Gestisci lead, automatizza i follow‑up e traccia le interazioni con i clienti con il CRM AUTOMEX. Semplifica il processo di vendita e fai crescere il tuo business.",
    nl: "Beheer leads, automatiseer follow‑ups en volg klantinteracties met AUTOMEX CRM. Stroomlijn uw verkoopproces en laat uw bedrijf groeien.",
    zh: "使用AUTOMEX CRM管理潜在客户、自动跟进并跟踪客户互动。优化销售流程，助您业务增长。",
    ar: "إدارة العملاء المحتملين، وأتمتة المتابعات، وتتبع تفاعلات العملاء مع AUTOMEX CRM. تبسيط عملية البيع وتنمية أعمالك.",
    fa: "سرنخ‌ها را مدیریت کنید، پیگیری‌ها را خودکار کنید و تعاملات مشتری را با AUTOMEX CRM ردیابی کنید. فرآیند فروش را ساده کنید و کسب‌وکار خود را رشد دهید.",
    ps: "د مشرانو مدیریت، تعقیبونه اتومات کړئ، او د AUTOMEX CRM سره د پیرودونکو تعاملات تعقیب کړئ. خپل د پلور پروسه ساده کړئ او خپل سوداګري پراخه کړئ.",
  },
  bookCall: {
    en: "Schedule a free consultation with our AI experts. Discuss your project, explore possibilities, and get a personalised roadmap from AUTOMEX.",
    es: "Programe una consulta gratuita con nuestros expertos en IA. Discuta su proyecto, explore posibilidades y obtenga una hoja de ruta personalizada de AUTOMEX.",
    de: "Vereinbaren Sie ein kostenloses Beratungsgespräch mit unseren KI-Experten. Besprechen Sie Ihr Projekt, entdecken Sie Möglichkeiten und erhalten Sie eine persönliche Roadmap von AUTOMEX.",
    fr: "Planifiez une consultation gratuite avec nos experts en IA. Discutez de votre projet, explorez les possibilités et obtenez une feuille de route personnalisée d’AUTOMEX.",
    it: "Prenota una consulenza gratuita con i nostri esperti di IA. Discuti il tuo progetto, esplora le possibilità e ottieni una roadmap personalizzata da AUTOMEX.",
    nl: "Plan een gratis consult met onze AI-experts. Bespreek uw project, verken mogelijkheden en ontvang een persoonlijke roadmap van AUTOMEX.",
    zh: "与我们的AI专家预约免费咨询。讨论您的项目，探索可能性，并获得AUTOMEX的个性化路线图。",
    ar: "حدد موعدًا لاستشارة مجانية مع خبراء الذكاء الاصطناعي لدينا. ناقش مشروعك، واستكشف الاحتمالات، واحصل على خارطة طريق مخصصة من AUTOMEX.",
    fa: "یک جلسه مشاوره رایگان با کارشناسان هوش مصنوعی ما رزرو کنید. درباره پروژه خود گفتگو کنید، احتمالات را بررسی کنید و یک نقشه راه شخصی‌سازی شده از AUTOMEX دریافت کنید.",
    ps: "زموږ د AI کارپوهانو سره وړیا مشوره وټاکئ. خپله پروژه وغږیږئ، امکانات وپلټئ، او د AUTOMEX څخه شخصي نقشه ترلاسه کړئ.",
  },
  contactSales: {
    en: "Get in touch with our sales team for enterprise‑grade AI solutions, custom software, and digital transformation services. We'll help you find the right package.",
    es: "Póngase en contacto con nuestro equipo de ventas para soluciones de IA de nivel empresarial, software personalizado y servicios de transformación digital. Le ayudaremos a encontrar el paquete adecuado.",
    de: "Kontaktieren Sie unser Vertriebsteam für KI-Lösungen auf Unternehmensniveau, maßgeschneiderte Software und digitale Transformationsdienste. Wir helfen Ihnen, das passende Paket zu finden.",
    fr: "Contactez notre équipe commerciale pour des solutions IA de niveau entreprise, des logiciels sur mesure et des services de transformation digitale. Nous vous aiderons à trouver le bon package.",
    it: "Mettiti in contatto con il nostro team di vendita per soluzioni IA di livello enterprise, software personalizzato e servizi di trasformazione digitale. Ti aiuteremo a trovare il pacchetto giusto.",
    nl: "Neem contact op met ons salesteam voor enterprise-grade AI-oplossingen, maatwerksoftware en digitale transformatiediensten. Wij helpen u het juiste pakket te vinden.",
    zh: "联系我们的销售团队，获取企业级AI解决方案、定制软件和数字化转型服务。我们将帮助您找到合适的方案。",
    ar: "تواصل مع فريق المبيعات لدينا للحصول على حلول ذكاء اصطناعي على مستوى المؤسسات، وبرمجيات مخصصة، وخدمات التحول الرقمي. سنساعدك في العثور على الباقة المناسبة.",
    fa: "برای راهکارهای هوش مصنوعی سازمانی، نرم‌افزار سفارشی و خدمات تحول دیجیتال با تیم فروش ما تماس بگیرید. ما به شما کمک می‌کنیم بسته مناسب را پیدا کنید.",
    ps: "د تصدۍ کچې AI حل لارو، دودیز سافټویر، او ډیجیټل بدلون خدمتونو لپاره زموږ د پلور ټیم سره اړیکه ونیسئ. موږ به تاسو سره د مناسب بسته موندلو کې مرسته وکړو.",
  },
  quote: {
    en: "Tell us about your project and receive a detailed, no‑obligation quote from AUTOMEX. We'll analyse your requirements and provide a transparent cost breakdown.",
    es: "Cuéntenos sobre su proyecto y reciba un presupuesto detallado y sin compromiso de AUTOMEX. Analizaremos sus requisitos y le proporcionaremos un desglose de costes transparente.",
    de: "Erzählen Sie uns von Ihrem Projekt und erhalten Sie ein detailliertes, unverbindliches Angebot von AUTOMEX. Wir analysieren Ihre Anforderungen und erstellen eine transparente Kostenaufstellung.",
    fr: "Parlez-nous de votre projet et recevez un devis détaillé et sans engagement d'AUTOMEX. Nous analyserons vos besoins et vous fournirons une répartition transparente des coûts.",
    it: "Raccontaci del tuo progetto e ricevi un preventivo dettagliato e senza impegno da AUTOMEX. Analizzeremo i tuoi requisiti e ti forniremo una ripartizione dei costi trasparente.",
    nl: "Vertel ons over uw project en ontvang een gedetailleerde, vrijblijvende offerte van AUTOMEX. Wij analyseren uw wensen en geven een transparante kostenspecificatie.",
    zh: "告诉我们您的项目，即可获得AUTOMEX提供的详细、无义务报价。我们将分析您的需求并提供透明的费用明细。",
    ar: "أخبرنا عن مشروعك واحصل على عرض سعر مفصل وغير ملزم من AUTOMEX. سنقوم بتحليل متطلباتك وتزويدك بتفصيل شفاف للتكاليف.",
    fa: "درباره پروژه خود به ما بگویید و یک پیش‌فاکتور دقیق و بدون تعهد از AUTOMEX دریافت کنید. ما نیازهای شما را تحلیل کرده و یک تفکیک هزینه شفاف ارائه می‌دهیم.",
    ps: "موږ ته د خپلې پروژې په اړه ووایاست او د AUTOMEX څخه مفصل، پرته له ژمنې نرخ ترلاسه کړئ. موږ به ستاسو اړتیاوې تحلیل کړو او یو روښانه لګښت تحلیل به درکړو.",
  },
  services: {
    en: "Explore AUTOMEX services — AI-powered software development, web & mobile apps, cloud solutions, and digital transformation consulting.",
    es: "Explore los servicios de AUTOMEX — desarrollo de software impulsado por IA, aplicaciones web y móviles, soluciones en la nube y consultoría de transformación digital.",
    de: "Entdecken Sie AUTOMEX-Dienste — KI-gestützte Softwareentwicklung, Web- und Mobile-Apps, Cloud-Lösungen und Beratung zur digitalen Transformation.",
    fr: "Découvrez les services AUTOMEX — développement logiciel alimenté par l'IA, applications web et mobiles, solutions cloud et conseil en transformation digitale.",
    it: "Esplora i servizi AUTOMEX — sviluppo software basato su IA, app web e mobili, soluzioni cloud e consulenza per la trasformazione digitale.",
    nl: "Ontdek AUTOMEX-diensten — AI-aangedreven softwareontwikkeling, web- en mobiele apps, cloudoplossingen en digitale transformatieadvies.",
    zh: "探索AUTOMEX服务——AI驱动的软件开发、网页与移动应用、云解决方案和数字化转型咨询。",
    ar: "استكشف خدمات AUTOMEX — تطوير البرمجيات المدعوم بالذكاء الاصطناعي، وتطبيقات الويب والجوال، والحلول السحابية، واستشارات التحول الرقمي.",
    fa: "خدمات AUTOMEX را کاوش کنید — توسعه نرم‌افزار مبتنی بر هوش مصنوعی، اپلیکیشن‌های وب و موبایل، راهکارهای ابری و مشاوره تحول دیجیتال.",
    ps: "د AUTOMEX خدمتونه وپلټئ — د AI ځواکمن سافټویر پراختیا، ویب او موبایل اپلیکیشنونه، کلاوډ حل لارې او ډیجیټل بدلون مشوره.",
  },
  serviceDetail: {
    en: "Learn more about this AUTOMEX service — AI-driven development, expert delivery, and tailored technology solutions for your business.",
    es: "Obtenga más información sobre este servicio de AUTOMEX — desarrollo impulsado por IA, entrega experta y soluciones tecnológicas a medida para su negocio.",
    de: "Erfahren Sie mehr über diesen AUTOMEX-Dienst — KI-gesteuerte Entwicklung, fachkundige Lieferung und maßgeschneiderte Technologielösungen für Ihr Unternehmen.",
    fr: "En savoir plus sur ce service AUTOMEX — développement piloté par l'IA, livraison experte et solutions technologiques sur mesure pour votre entreprise.",
    it: "Scopri di più su questo servizio AUTOMEX — sviluppo guidato dall'IA, consegna esperta e soluzioni tecnologiche su misura per la tua azienda.",
    nl: "Lees meer over deze AUTOMEX-service — AI-gestuurde ontwikkeling, deskundige oplevering en op maat gemaakte technologieoplossingen voor uw bedrijf.",
    zh: "了解更多关于此AUTOMEX服务——AI驱动开发、专业交付以及为您的企业量身定制的技术解决方案。",
    ar: "تعرف على المزيد حول خدمة AUTOMEX هذه — تطوير مدعوم بالذكاء الاصطناعي، وتسليم خبير، وحلول تقنية مخصصة لعملك.",
    fa: "درباره این سرویس AUTOMEX بیشتر بدانید — توسعه مبتنی بر هوش مصنوعی، تحویل تخصصی و راهکارهای فناوری متناسب با کسب‌وکار شما.",
    ps: "د دې AUTOMEX خدمت په اړه نور معلومات ترلاسه کړئ — د AI لخوا پرمخ وړل شوې پراختیا، متخصص تحویل، او ستاسو سوداګرۍ لپاره مناسب ټکنالوژۍ حل لارې.",
  },
  techExpertise: {
    en: "Explore AUTOMEX technology expertise across architecture, cloud, AI, data engineering, DevOps, mobile, security, and QA — the full stack skills behind every successful project.",
    es: "Explore la experiencia tecnológica de AUTOMEX en arquitectura, cloud, IA, ingeniería de datos, DevOps, móvil, seguridad y QA — las habilidades de stack completo detrás de cada proyecto exitoso.",
    de: "Entdecken Sie die Technologie-Expertise von AUTOMEX in Architektur, Cloud, KI, Data Engineering, DevOps, Mobile, Sicherheit und QA — die Full-Stack-Fähigkeiten hinter jedem erfolgreichen Projekt.",
    fr: "Explorez l'expertise technologique d'AUTOMEX en architecture, cloud, IA, ingénierie des données, DevOps, mobile, sécurité et QA — les compétences full-stack derrière chaque projet réussi.",
    it: "Esplora le competenze tecnologiche di AUTOMEX in architettura, cloud, IA, ingegneria dei dati, DevOps, mobile, sicurezza e QA — le competenze full-stack dietro ogni progetto di successo.",
    nl: "Ontdek de technologie-expertise van AUTOMEX in architectuur, cloud, AI, data engineering, DevOps, mobiel, beveiliging en QA — de full-stack vaardigheden achter elk succesvol project.",
    zh: "探索AUTOMEX在架构、云、AI、数据工程、DevOps、移动、安全和QA方面的技术专长——每个成功项目背后的全栈技能。",
    ar: "استكشف خبرة AUTOMEX التقنية في الهندسة المعمارية والسحابة والذكاء الاصطناعي وهندسة البيانات وDevOps والجوال والأمان وضمان الجودة — المهارات الكاملة وراء كل مشروع ناجح.",
    fa: "تخصص فناوری AUTOMEX را در معماری، ابر، هوش مصنوعی، مهندسی داده، DevOps، موبایل، امنیت و QA کاوش کنید — مهارت‌های کامل پشته پشت هر پروژه موفق.",
    ps: "د AUTOMEX ټکنالوژۍ تخصص په معمارۍ، کلاوډ، AI، ډیټا انجینرۍ، DevOps، موبایل، امنیت او QA کې وپلټئ — د هرې بریالۍ پروژې تر شا د بشپړ سټک مهارتونه.",
  },
  techExpertiseDetail: {
    en: "Learn about this AUTOMEX technology expertise area — the tools, frameworks, and methodologies we use to deliver production-grade software and infrastructure.",
    es: "Conozca esta área de experiencia tecnológica de AUTOMEX — las herramientas, frameworks y metodologías que utilizamos para entregar software e infraestructura de nivel de producción.",
    de: "Erfahren Sie mehr über diesen Technologie-Expertisebereich von AUTOMEX — die Tools, Frameworks und Methoden, mit denen wir produktionsreife Software und Infrastruktur liefern.",
    fr: "Découvrez ce domaine d'expertise technologique d'AUTOMEX — les outils, frameworks et méthodologies que nous utilisons pour livrer des logiciels et une infrastructure de qualité production.",
    it: "Scopri quest'area di competenza tecnologica di AUTOMEX — gli strumenti, i framework e le metodologie che utilizziamo per fornire software e infrastrutture di livello produzione.",
    nl: "Leer over dit technologie-expertisegebied van AUTOMEX — de tools, frameworks en methodologieën die wij gebruiken om productieklare software en infrastructuur te leveren.",
    zh: "了解AUTOMEX的这项技术专长领域——我们用于交付生产级软件和基础设施的工具、框架和方法论。",
    ar: "تعرف على مجال الخبرة التقنية هذا من AUTOMEX — الأدوات والأطر والمنهجيات التي نستخدمها لتقديم برمجيات وبنية تحتية على مستوى الإنتاج.",
    fa: "درباره این حوزه تخصص فناوری AUTOMEX بیاموزید — ابزارها، فریم‌ورک‌ها و روش‌شناسی‌هایی که برای ارائه نرم‌افزار و زیرساخت در سطح تولید استفاده می‌کنیم.",
    ps: "د AUTOMEX د دې ټکنالوژۍ تخصص ساحې په اړه زده کړئ — هغه وسیلې، چوکاټونه او میتودولوژي چې موږ یې د تولید کچې سافټویر او زیربنا وړاندې کولو لپاره کاروو.",
  },
  industries: {
    en: "Explore AUTOMEX industry expertise across healthcare, e-commerce, SaaS, and more. Tailored AI and technology solutions for every sector.",
    es: "Explore la experiencia industrial de AUTOMEX en salud, comercio electrónico, SaaS y más. Soluciones de IA y tecnología adaptadas a cada sector.",
    de: "Entdecken Sie die Branchenexpertise von AUTOMEX in Gesundheitswesen, E-Commerce, SaaS und mehr. Maßgeschneiderte KI- und Technologielösungen für jede Branche.",
    fr: "Explorez l'expertise sectorielle d'AUTOMEX dans la santé, le e-commerce, le SaaS et plus encore. Solutions IA et technologiques adaptées à chaque secteur.",
    it: "Esplora l'esperienza industriale di AUTOMEX in sanità, e-commerce, SaaS e altro. Soluzioni IA e tecnologiche su misura per ogni settore.",
    nl: "Ontdek de branche-expertise van AUTOMEX in de gezondheidszorg, e-commerce, SaaS en meer. Op maat gemaakte AI- en technologieoplossingen voor elke sector.",
    zh: "探索AUTOMEX在医疗、电子商务、SaaS等领域的行业专长。为每个行业量身定制的AI和技术解决方案。",
    ar: "استكشف خبرة AUTOMEX الصناعية في الرعاية الصحية والتجارة الإلكترونية وSaaS والمزيد. حلول الذكاء الاصطناعي والتكنولوجيا المصممة لكل قطاع.",
    fa: "تخصص صنعتی AUTOMEX را در بهداشت و درمان، تجارت الکترونیک، SaaS و بیشتر کاوش کنید. راهکارهای هوش مصنوعی و فناوری متناسب با هر بخش.",
    ps: "د روغتیا پاملرنې، ای کامرس، SaaS او نورو برخو کې د AUTOMEX صنعتي تخصص وپلټئ. د هر سکټور لپاره مناسب AI او ټکنالوژۍ حل لارې.",
  },
  industryDetail: {
    en: "Learn how AUTOMEX delivers AI and software solutions for this industry — tailored technology, compliance expertise, and proven results.",
    es: "Descubra cómo AUTOMEX ofrece soluciones de IA y software para esta industria — tecnología a medida, experiencia en cumplimiento y resultados comprobados.",
    de: "Erfahren Sie, wie AUTOMEX KI- und Softwarelösungen für diese Branche liefert — maßgeschneiderte Technologie, Compliance-Expertise und bewährte Ergebnisse.",
    fr: "Découvrez comment AUTOMEX fournit des solutions IA et logicielles pour cette industrie — technologie sur mesure, expertise en conformité et résultats éprouvés.",
    it: "Scopri come AUTOMEX fornisce soluzioni IA e software per questo settore — tecnologia su misura, competenza in conformità e risultati comprovati.",
    nl: "Ontdek hoe AUTOMEX AI- en softwareoplossingen voor deze branche levert — op maat gemaakte technologie, compliance-expertise en bewezen resultaten.",
    zh: "了解AUTOMEX如何为该行业提供AI和软件解决方案——定制技术、合规专业知识和经证实的成果。",
    ar: "تعرف على كيفية تقديم AUTOMEX لحلول الذكاء الاصطناعي والبرمجيات لهذه الصناعة — تقنية مخصصة وخبرة في الامتثال ونتائج مثبتة.",
    fa: "بیاموزید که AUTOMEX چگونه راهکارهای هوش مصنوعی و نرم‌افزاری برای این صنعت ارائه می‌دهد — فناوری سفارشی، تخصص انطباق و نتایج اثبات شده.",
    ps: "زده کړئ چې AUTOMEX څنګه د دې صنعت لپاره AI او سافټویر حل لارې وړاندې کوي — مناسب ټکنالوژي، د موافقت تخصص، او ثابت شوي پایلې.",
  },
  aiCapabilities: {
    en: "Explore AUTOMEX AI capabilities — NLP, Computer Vision, Generative AI, Predictive Analytics, MLOps, RAG agents, and intelligent automation.",
    es: "Explore las capacidades de IA de AUTOMEX — NLP, Visión por Computadora, IA Generativa, Analítica Predictiva, MLOps, agentes RAG y automatización inteligente.",
    de: "Entdecken Sie die KI-Fähigkeiten von AUTOMEX — NLP, Computer Vision, generative KI, prädiktive Analytik, MLOps, RAG-Agenten und intelligente Automatisierung.",
    fr: "Explorez les capacités IA d'AUTOMEX — NLP, vision par ordinateur, IA générative, analytique prédictive, MLOps, agents RAG et automatisation intelligente.",
    it: "Esplora le capacità IA di AUTOMEX — NLP, visione artificiale, IA generativa, analisi predittiva, MLOps, agenti RAG e automazione intelligente.",
    nl: "Ontdek de AI-mogelijkheden van AUTOMEX — NLP, computer vision, generatieve AI, voorspellende analyse, MLOps, RAG-agenten en intelligente automatisering.",
    zh: "探索AUTOMEX的AI能力——NLP、计算机视觉、生成式AI、预测分析、MLOps、RAG代理和智能自动化。",
    ar: "استكشف قدرات الذكاء الاصطناعي لدى AUTOMEX — معالجة اللغة الطبيعية، الرؤية الحاسوبية، الذكاء الاصطناعي التوليدي، التحليلات التنبؤية، MLOps، وكلاء RAG، والأتمتة الذكية.",
    fa: "قابلیت‌های هوش مصنوعی AUTOMEX را کاوش کنید — NLP، بینایی کامپیوتر، هوش مصنوعی مولد، تحلیل پیش‌بینانه، MLOps، عامل‌های RAG و اتوماسیون هوشمند.",
    ps: "د AUTOMEX د AI وړتیاوې وپلټئ — NLP، کمپیوټر لید، تولیدي AI، وړاندوینه‌يیز تحلیل، MLOps، RAG اجنټان، او هوښیار اتومات کول.",
  },
  aiCapabilityDetail: {
    en: "Learn about this AUTOMEX AI capability — how we apply cutting-edge artificial intelligence to solve real-world business challenges.",
    es: "Conozca esta capacidad de IA de AUTOMEX — cómo aplicamos inteligencia artificial de vanguardia para resolver desafíos empresariales reales.",
    de: "Erfahren Sie mehr über diese KI-Fähigkeit von AUTOMEX — wie wir modernste künstliche Intelligenz zur Lösung realer Geschäftsprobleme einsetzen.",
    fr: "Découvrez cette capacité IA d'AUTOMEX — comment nous appliquons l'intelligence artificielle de pointe pour résoudre des défis commerciaux réels.",
    it: "Scopri questa capacità IA di AUTOMEX — come applichiamo l'intelligenza artificiale all'avanguardia per risolvere sfide aziendali reali.",
    nl: "Leer over deze AI-mogelijkheid van AUTOMEX — hoe wij geavanceerde kunstmatige intelligentie toepassen om echte bedrijfsuitdagingen op te lossen.",
    zh: "了解AUTOMEX的这项AI能力——我们如何应用尖端人工智能解决现实世界的商业挑战。",
    ar: "تعرف على قدرة الذكاء الاصطناعي هذه من AUTOMEX — كيف نطبق الذكاء الاصطناعي المتطور لحل تحديات الأعمال الحقيقية.",
    fa: "درباره این قابلیت هوش مصنوعی AUTOMEX بیاموزید — چگونه هوش مصنوعی پیشرفته را برای حل چالش‌های واقعی کسب‌وکار به کار می‌گیریم.",
    ps: "د AUTOMEX د دې AI وړتیا په اړه زده کړئ — څنګه موږ د ریښتیني نړۍ سوداګریزې ننګونې حل کولو لپاره عصري مصنوعي ځیرکتیا پلي کوو.",
  },
  caseStudies: {
    en: "Explore AUTOMEX case studies showcasing AI solutions, custom software, and digital transformation across industries. Real projects, real results.",
    es: "Explore los casos de estudio de AUTOMEX que muestran soluciones de IA, software personalizado y transformación digital en todas las industrias. Proyectos reales, resultados reales.",
    de: "Entdecken Sie AUTOMEX-Fallstudien, die KI-Lösungen, maßgeschneiderte Software und digitale Transformation in verschiedenen Branchen präsentieren. Echte Projekte, echte Ergebnisse.",
    fr: "Explorez les études de cas AUTOMEX présentant des solutions IA, des logiciels personnalisés et la transformation digitale dans tous les secteurs. De vrais projets, de vrais résultats.",
    it: "Esplora i casi studio AUTOMEX che mostrano soluzioni IA, software personalizzato e trasformazione digitale in tutti i settori. Progetti reali, risultati reali.",
    nl: "Ontdek AUTOMEX-casestudies die AI-oplossingen, maatwerksoftware en digitale transformatie in verschillende branches presenteren. Echte projecten, echte resultaten.",
    zh: "探索AUTOMEX案例研究，展示跨行业的AI解决方案、定制软件和数字化转型。真实项目，真实成果。",
    ar: "استكشف دراسات الحالة من AUTOMEX التي تعرض حلول الذكاء الاصطناعي والبرمجيات المخصصة والتحول الرقمي عبر الصناعات. مشاريع حقيقية، نتائج حقيقية.",
    fa: "مطالعات موردی AUTOMEX را کاوش کنید که راهکارهای هوش مصنوعی، نرم‌افزار سفارشی و تحول دیجیتال را در صنایع مختلف نشان می‌دهند. پروژه‌های واقعی، نتایج واقعی.",
    ps: "د AUTOMEX د قضیې مطالعې وپلټئ چې په صنعتونو کې د AI حل لارې، دودیز سافټویر او ډیجیټل بدلون ښیي. ریښتیني پروژې، ریښتیني پایلې.",
  },
  caseStudyDetail: {
    en: "Read this AUTOMEX case study for an in-depth look at how we delivered AI and software solutions — challenge, solution, results, and technology stack.",
    es: "Lea este caso de estudio de AUTOMEX para un análisis en profundidad de cómo entregamos soluciones de IA y software — desafío, solución, resultados y stack tecnológico.",
    de: "Lesen Sie diese AUTOMEX-Fallstudie für einen detaillierten Einblick, wie wir KI- und Softwarelösungen geliefert haben — Herausforderung, Lösung, Ergebnisse und Technologie-Stack.",
    fr: "Lisez cette étude de cas AUTOMEX pour un aperçu approfondi de la façon dont nous avons livré des solutions IA et logicielles — défi, solution, résultats et stack technologique.",
    it: "Leggi questo caso studio AUTOMEX per uno sguardo approfondito su come abbiamo fornito soluzioni IA e software — sfida, soluzione, risultati e stack tecnologico.",
    nl: "Lees deze AUTOMEX-casestudie voor een diepgaande kijk op hoe wij AI- en softwareoplossingen hebben geleverd — uitdaging, oplossing, resultaten en technologie-stack.",
    zh: "阅读这篇AUTOMEX案例研究，深入了解我们如何交付AI和软件解决方案——挑战、解决方案、成果和技术栈。",
    ar: "اقرأ دراسة الحالة هذه من AUTOMEX للحصول على نظرة متعمقة حول كيفية تقديمنا لحلول الذكاء الاصطناعي والبرمجيات — التحدي والحل والنتائج والمكدس التقني.",
    fa: "این مطالعه موردی AUTOMEX را برای نگاهی عمیق به نحوه ارائه راهکارهای هوش مصنوعی و نرم‌افزاری ما بخوانید — چالش، راه حل، نتایج و پشته فناوری.",
    ps: "دا AUTOMEX د قضیې مطالعه ولولئ د دې په اړه ژور نظر لپاره چې موږ څنګه AI او سافټویر حل لارې وړاندې کړې — ننګونه، حل، پایلې او ټکنالوژۍ سټیک.",
  },
  portfolio: {
    en: "Browse AUTOMEX portfolio of custom software, AI solutions, and digital transformation projects across industries. See our work for startups, enterprises, and global brands.",
    es: "Explore el portafolio de AUTOMEX de software personalizado, soluciones de IA y proyectos de transformación digital en todas las industrias. Vea nuestro trabajo para startups, empresas y marcas globales.",
    de: "Durchstöbern Sie das AUTOMEX-Portfolio mit maßgeschneiderter Software, KI-Lösungen und Projekten zur digitalen Transformation in verschiedenen Branchen. Sehen Sie unsere Arbeit für Startups, Unternehmen und globale Marken.",
    fr: "Parcourez le portfolio AUTOMEX de logiciels personnalisés, de solutions IA et de projets de transformation digitale dans tous les secteurs. Découvrez notre travail pour les startups, les entreprises et les marques mondiales.",
    it: "Sfoglia il portfolio AUTOMEX di software personalizzato, soluzioni IA e progetti di trasformazione digitale in tutti i settori. Guarda il nostro lavoro per startup, imprese e marchi globali.",
    nl: "Blader door het AUTOMEX-portfolio van maatwerksoftware, AI-oplossingen en digitale transformatieprojecten in verschillende branches. Bekijk ons werk voor startups, ondernemingen en wereldwijde merken.",
    zh: "浏览AUTOMEX跨行业的定制软件、AI解决方案和数字化转型项目作品集。查看我们为初创企业、大型企业和全球品牌所做的工作。",
    ar: "تصفح محفظة AUTOMEX من البرمجيات المخصصة وحلول الذكاء الاصطناعي ومشاريع التحول الرقمي عبر الصناعات. شاهد عملنا للشركات الناشئة والمؤسسات والعلامات التجارية العالمية.",
    fa: "نمونه کارهای AUTOMEX از نرم‌افزار سفارشی، راهکارهای هوش مصنوعی و پروژه‌های تحول دیجیتال در صنایع مختلف را مرور کنید. کار ما برای استارتاپ‌ها، سازمان‌ها و برندهای جهانی را ببینید.",
    ps: "د صنعتونو په اوږدو کې د AUTOMEX دودیز سافټویر، AI حل لارو او ډیجیټل بدلون پروژو پورټ فولیو وګورئ. د پیلو، تصدیو او نړیوالو برانډونو لپاره زموږ کار وګورئ.",
  },
  portfolioDetail: {
    en: "Explore this AUTOMEX portfolio project — technology stack, client results, gallery images, and services delivered for successful digital transformation.",
    es: "Explore este proyecto del portafolio de AUTOMEX — stack tecnológico, resultados del cliente, imágenes de la galería y servicios entregados para una transformación digital exitosa.",
    de: "Entdecken Sie dieses AUTOMEX-Portfolio-Projekt — Technologie-Stack, Kundenergebnisse, Galeriebilder und gelieferte Dienstleistungen für eine erfolgreiche digitale Transformation.",
    fr: "Explorez ce projet du portfolio AUTOMEX — stack technologique, résultats clients, images de la galerie et services fournis pour une transformation digitale réussie.",
    it: "Esplora questo progetto del portfolio AUTOMEX — stack tecnologico, risultati del cliente, immagini della galleria e servizi forniti per una trasformazione digitale di successo.",
    nl: "Verken dit AUTOMEX-portfolioproject — technologiestack, klantresultaten, galerijafbeeldingen en geleverde diensten voor een succesvolle digitale transformatie.",
    zh: "探索这个AUTOMEX作品集项目——技术栈、客户成果、图库图片以及为成功数字化转型提供的服务。",
    ar: "استكشف مشروع محفظة AUTOMEX هذا — مجموعة التقنيات ونتائج العملاء وصور المعرض والخدمات المقدمة لتحول رقمي ناجح.",
    fa: "این پروژه نمونه کار AUTOMEX را کاوش کنید — پشته فناوری، نتایج مشتری، تصاویر گالری و خدمات ارائه شده برای تحول دیجیتال موفق.",
    ps: "د AUTOMEX دا پورټ فولیو پروژه وپلټئ — ټکنالوژۍ سټک، د پیرودونکي پایلې، ګالري انځورونه، او د بریالي ډیجیټل بدلون لپاره وړاندې شوي خدمتونه.",
  },
  blog: {
    en: "Read the latest articles, tutorials, and insights on AI, software development, cloud computing, and digital transformation from the AUTOMEX engineering team.",
    es: "Lea los últimos artículos, tutoriales y perspectivas sobre IA, desarrollo de software, computación en la nube y transformación digital del equipo de ingeniería de AUTOMEX.",
    de: "Lesen Sie die neuesten Artikel, Tutorials und Einblicke zu KI, Softwareentwicklung, Cloud Computing und digitaler Transformation vom AUTOMEX-Entwicklerteam.",
    fr: "Lisez les derniers articles, tutoriels et perspectives sur l'IA, le développement logiciel, le cloud computing et la transformation digitale de l'équipe d'ingénierie AUTOMEX.",
    it: "Leggi gli ultimi articoli, tutorial e approfondimenti su IA, sviluppo software, cloud computing e trasformazione digitale dal team di ingegneria AUTOMEX.",
    nl: "Lees de nieuwste artikelen, tutorials en inzichten over AI, softwareontwikkeling, cloud computing en digitale transformatie van het AUTOMEX-engineeringteam.",
    zh: "阅读AUTOMEX工程团队关于AI、软件开发、云计算和数字化转型的最新文章、教程和见解。",
    ar: "اقرأ أحدث المقالات والدروس والرؤى حول الذكاء الاصطناعي وتطوير البرمجيات والحوسبة السحابية والتحول الرقمي من فريق هندسة AUTOMEX.",
    fa: "آخرین مقالات، آموزش‌ها و بینش‌های مربوط به هوش مصنوعی، توسعه نرم‌افزار، رایانش ابری و تحول دیجیتال را از تیم مهندسی AUTOMEX بخوانید.",
    ps: "د AUTOMEX انجینرۍ ټیم څخه د AI، سافټویر پراختیا، کلاوډ کمپیوټنګ، او ډیجیټل بدلون په اړه وروستي مقالې، ښوونې او لیدونه ولولئ.",
  },
  blogDetail: {
    en: "Read this AUTOMEX blog article for expert insights on technology, software development, and AI solutions.",
    es: "Lea este artículo del blog de AUTOMEX para obtener información experta sobre tecnología, desarrollo de software y soluciones de IA.",
    de: "Lesen Sie diesen AUTOMEX-Blogartikel für Experteneinblicke zu Technologie, Softwareentwicklung und KI-Lösungen.",
    fr: "Lisez cet article du blog AUTOMEX pour des perspectives d'experts sur la technologie, le développement logiciel et les solutions IA.",
    it: "Leggi questo articolo del blog AUTOMEX per approfondimenti esperti su tecnologia, sviluppo software e soluzioni IA.",
    nl: "Lees dit AUTOMEX-blogartikel voor deskundige inzichten over technologie, softwareontwikkeling en AI-oplossingen.",
    zh: "阅读这篇AUTOMEX博客文章，获取关于技术、软件开发和AI解决方案的专家见解。",
    ar: "اقرأ مقالة مدونة AUTOMEX هذه للحصول على رؤى خبراء حول التكنولوجيا وتطوير البرمجيات وحلول الذكاء الاصطناعي.",
    fa: "این مقاله وبلاگ AUTOMEX را برای بینش‌های تخصصی در مورد فناوری، توسعه نرم‌افزار و راهکارهای هوش مصنوعی بخوانید.",
    ps: "د ټکنالوژۍ، سافټویر پراختیا او AI حل لارو په اړه د کارپوهانو لیدونو لپاره دا AUTOMEX بلاګ مقاله ولولئ.",
  },
  privacy: {
    en: "Learn how AUTOMEX collects, uses, and protects your personal information. Effective July 2025.",
    es: "Conozca cómo AUTOMEX recopila, utiliza y protege su información personal. Vigente desde julio de 2025.",
    de: "Erfahren Sie, wie AUTOMEX Ihre persönlichen Daten erhebt, verwendet und schützt. Gültig ab Juli 2025.",
    fr: "Découvrez comment AUTOMEX collecte, utilise et protège vos informations personnelles. En vigueur depuis juillet 2025.",
    it: "Scopri come AUTOMEX raccoglie, utilizza e protegge le tue informazioni personali. In vigore da luglio 2025.",
    nl: "Lees hoe AUTOMEX uw persoonlijke gegevens verzamelt, gebruikt en beschermt. Geldig vanaf juli 2025.",
    zh: "了解AUTOMEX如何收集、使用和保护您的个人信息。自2025年7月起生效。",
    ar: "تعرف على كيفية جمع AUTOMEX واستخدامها وحماية معلوماتك الشخصية. ساري اعتبارًا من يوليو 2025.",
    fa: "نحوه جمع، استفاده و محافظت AUTOMEX از اطلاعات شخصی شما را بیاموزید. معتبر از ژوئیه 2025.",
    ps: "زده کړئ چې AUTOMEX څنګه ستاسو شخصي معلومات راټولوي، کاروي او ساتي. د جولای 2025 څخه اغیزمن.",
  },
  terms: {
    en: "Read the Terms of Service for AUTOMEX. Understand your rights and obligations when using our AI and software services.",
    es: "Lea los Términos de Servicio de AUTOMEX. Comprenda sus derechos y obligaciones al usar nuestros servicios de IA y software.",
    de: "Lesen Sie die Nutzungsbedingungen von AUTOMEX. Verstehen Sie Ihre Rechte und Pflichten bei der Nutzung unserer KI- und Software-Dienste.",
    fr: "Lisez les Conditions d'Utilisation d'AUTOMEX. Comprenez vos droits et obligations lors de l'utilisation de nos services IA et logiciels.",
    it: "Leggi i Termini di Servizio di AUTOMEX. Comprendi i tuoi diritti e obblighi quando utilizzi i nostri servizi IA e software.",
    nl: "Lees de Algemene Voorwaarden van AUTOMEX. Begrijp uw rechten en verplichtingen bij het gebruik van onze AI- en softwarediensten.",
    zh: "阅读AUTOMEX的服务条款。了解您在使用我们的AI和软件服务时的权利和义务。",
    ar: "اقرأ شروط الخدمة الخاصة بـ AUTOMEX. افهم حقوقك والتزاماتك عند استخدام خدمات الذكاء الاصطناعي والبرمجيات لدينا.",
    fa: "شرایط خدمات AUTOMEX را بخوانید. حقوق و تعهدات خود را هنگام استفاده از خدمات هوش مصنوعی و نرم‌افزار ما درک کنید.",
    ps: "د AUTOMEX د خدماتو شرایط ولولئ. زموږ د AI او سافټویر خدمتونو کارولو پر مهال خپل حقونه او مکلفیتونه وپوهئ.",
  },
};

export function generatePageMetadata(options: SeoMetadataOptions): Metadata {
  const {
    pageType,
    locale,
    pathSegment,
    customTitle,
    customDescription,
    ogImageUrl,
    ogImageAlt,
    canonicalUrl,
    noIndex = false,
  } = options;

  const titleTemplate = titleTemplates[pageType]?.[locale as SupportedLocale] || titleTemplates.home.en;
  const descriptionTemplate = defaultDescriptions[pageType]?.[locale as SupportedLocale] || defaultDescriptions.home.en;

  let title = customTitle || titleTemplate;
  let description = customDescription || descriptionTemplate;

  const keywords = getKeywords({
    locale: locale as SupportedLocale,
    pageType,
  });

  const alternates = getAlternates({
    locale: locale as SupportedLocale,
    pathSegment,
  });

  const image = ogImageUrl || `${BASE_URL}/logo/automex.png`;
  const imageAlt = ogImageAlt || title;

  const metadata: Metadata = {
    title,
    description,
    keywords: keywords.join(", "),
    alternates,
    openGraph: {
      title,
      description,
      url: `${BASE_URL}/${locale}${pathSegment ? `/${pathSegment}` : ""}`,
      siteName: "AUTOMEX",
      locale: getOgLocale(locale),
      type: "website",
      images: [{ url: image, width: 1200, height: 630, alt: imageAlt }],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [image],
    },
    robots: {
      index: !noIndex,
      follow: !noIndex,
      "max-snippet": -1,
      "max-image-preview": "large",
      "max-video-preview": -1,
    },
  };

  if (canonicalUrl) {
    metadata.alternates = {
      ...metadata.alternates,
      canonical: canonicalUrl,
    };
  }

  return metadata;
}